### ISSUE TITLE
Cannot deploy stepf function when using yml variables

### ISSUE THREAD

**Issue by GuidoS** [horike37/serverless-step-functions#103]
# This is a Bug Report

## Description
When I use **Reference Properties** variables in my serverless.yml. after debugging this a little I found that the iam.js was passing the role name as a combination of region and stage values that showed my variable ${} code instead of the values assoriated with those codes.

I think this is a bug because I am able to deploy the rest of the serverless package without an issue and the variables resolved correctly. 

I also tried hard coding the variables and that seemed to work, but it makes setting up a dev/production workflow impossible.

Thanks in advance for any help you can provide for this issue.

## What went wrong?

I cannot deploy my stepf functions

## What did you expect should have happened?

stepf functions should deploy

## What was the config you used?

```yml
provider:
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.regions.${self:provider.stage}}

custom:
  defaultStage: dev
  regions:
    dev: us-east-2
    pro: us-east-1
```

## What stacktrace or error message from your provider did you see?

```
  Serverless Error ---------------------------------------

  The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-

  Stack Trace --------------------------------------------

ServerlessError: The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-
    at provider.request.then.catch (/Users/gstein/git/appgeo/nfpa_2017-1497.nationalfiredatasystem/nfds/node_modules/serverless-step-functions/lib/iam.js:61:13)
From previous event:
    at ServerlessStepFunctions.getIamRole (/Users/gstein/git/appgeo/nfpa_2017-1497.nationalfiredatasystem/nfds/node_modules/serverless-step-functions/lib/iam.js:57:13)
    at BbPromise.map (/Users/gstein/git/appgeo/nfpa_2017-1497.nationalfiredatasystem/nfds/node_modules/serverless-step-functions/lib/iam.js:71:52)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

## Additional Data
* ***Serverless Framework Core Version you're using***:
    * 1.25.0

* ***The Plugin Version you're using***:
   * 0.3.0

* ***Operating System***:
    * darmin

**Comment by GuidoS** [comment]
Is there anything I can do to help escalate or solve this issue? I have not built serverless plugins before, but would be willing to learn to solve this problem.

**Comment by horike37** [comment]
Thank you for reporting @GuidoS :+1: 
That may be a bug as you said.
Could you share your whole serverless.yml file so that we can reproduce it ?

**Comment by GuidoS** [comment]
Here is my yml:
```yml
service: this-service

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DEBUG: "this-service:*"
  timeout: 300
  memorySize: 3008
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: ${self:custom.regions.${self:provider.stage}}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.prefix.bucket.${self:provider.stage}}this-service-submit/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.prefix.bucket.${self:provider.stage}}this-service-validate/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.prefix.bucket.${self:provider.stage}}this-service-asset/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.prefix.bucket.${self:provider.stage}}this-service-consolidate/*"
    - Effect: "Allow"
      Action:
        - "states:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "glue:*"
      Resource: "*"


functions:
  # s3 bucket triggers
  submit:
    handler: handler.runStep
    events:
      - s3: submit
    environment:
      STEP_FUNCTION_NAME: ${self:custom.prefix.function}-step-submit
  validate:
    handler: handler.runStep
    environment:
      STEP_FUNCTION_NAME: ${self:custom.prefix.function}-step-validate
    events:
      - s3:
          bucket: ${self:custom.prefix.bucket.${self:provider.stage}}this-service-validate
          event: s3:ObjectCreated:*
  consolidate:
    handler: handler.runStep
    environment:
      STEP_FUNCTION_NAME: ${self:custom.prefix.function}-step-consolidate
    events:
      - s3:
          bucket: ${self:custom.prefix.bucket.${self:provider.stage}}this-service-consolidate
          event: s3:ObjectCreated:*
  reportStep:
    handler: handler.reportStep

  # misc StepFunctions
  stepReport:
    handler: handler.stepReport

  # step submit task functions
  setupSubmitInfo:
    handler: stepSubmit.setupSubmitInfo
  isZipFile:
    handler: stepSubmit.isZipFile
  copyFileToValidate:
    handler: stepSubmit.copyFile
    environment:
      DESTINATION_BUCKET: ${self:custom.prefix.bucket.${self:provider.stage}}this-service-validate
  getZipList:
    handler: stepSubmit.getZipList
  unZipFile:
    handler: stepSubmit.unZipFile
    environment:
      DESTINATION_BUCKET: ${self:custom.prefix.bucket.${self:provider.stage}}this-service-validate
  catchUnzipFile:
    handler: stepSubmit.catchUnzipFile

  # step validate task stepFunctions
  setupValidateInfo:
    handler: stepValidate.setupValidateInfo
  determineSchema:
    handler: stepValidate.determineSchema
  profileCSV:
    handler: stepValidate.profileCSV
  determineFileType:
    handler: stepValidate.determineFileType
  determineDelimiter:
    handler: stepValidate.determineDelimiter
  moveFileToStructuredRepo:
    handler: stepValidate.moveFileToStructuredRepo
    environment:
      DESTINATION_BUCKET: ${self:custom.prefix.bucket.${self:provider.stage}}this-service-consolidate
  moveFileToUnStructuredRepo:
    handler: stepValidate.moveFileToUnStructuredRepo


  # step consolidatetask stepFunctions
  startCrawler:
    handler: stepConsolidate.startCrawler

stepFunctions:
  stateMachines:

    step-submit:
      StartAt: SetupSubmitInfo
      States:
        SetupSubmitInfo:
          Type: Task
          Resource: setupSubmitInfo
          Next: IsZipFile
        IsZipFile:
          Type: Task
          Resource: isZipFile
          Next: IsZipFileChoice
        IsZipFileChoice:
          Type: Choice
          Choices:
          - Variable: "$.stepMetaData.isZipFile"
            BooleanEquals: true
            Next: GetZipList
          Default: CopyFileToValidate
        CopyFileToValidate:
          Type: Task
          Resource: copyFileToValidate
          Next: Done
        GetZipList:
          Type: Task
          Resource: getZipList
          Next: UnZipFileToValidate
        UnZipFileToValidate:
          Type: Task
          Resource: unZipFile
          Next: UnZipFilesCompleted
          Retry:
            - ErrorEquals:
              - States.ALL
              IntervalSeconds: 1
              MaxAttempts: 2
              BackoffRate: 2.0
          Catch:
            - ErrorEquals:
              - States.ALL
              ResultPath: "$.unzipFailedError"
              Next: CatchUnZipError
        CatchUnZipError:
          Type: Task
          Resource: catchUnzipFile
          Next: UnZipFilesCompleted
        UnZipFilesCompleted:
          Type: Choice
          Choices:
          - Variable: "$.ZipFileQueueCount"
            NumericLessThan: 1
            Next: Done
          Default: UnZipFileToValidate
        Done:
          Type: Task
          Resource: stepReport
          End: true

    step-validate:
      StartAt: SetupValidateInfo
      States:
        SetupValidateInfo:
          Type: Task
          Resource: setupValidateInfo
          Next: DetermineFileType
        DetermineFileType:
          Type: Task
          Resource: determineFileType
          Next: FileTypeChoice
        FileTypeChoice:
          Type: Choice
          Choices:
          - Variable: "$.stepMetaData.fileType"
            StringEquals: 'txt'
            Next: DetermineDelimiter
          - Variable: "$.stepMetaData.fileType"
            StringEquals: 'csv'
            Next: ProfileCSV
          Default: MoveFileToObjectBucket
        MoveFileToObjectBucket:
          Type: Task
          Resource: moveFileToObjectBucket
          Next: Done
        DetermineDelimiter:
          Type: Task
          Resource: determineDelimiter
          Next: ProfileCSV
        ProfileCSV:
          Type: Task
          Resource: profileCSV
          Next: DetermineSchema
        DetermineSchema:
          Type: Task
          Resource: determineSchema
          Next: SchemaChoice
        SchemaChoice:
          Type: Choice
          Choices:
          - Variable: "$.stepMetaData.fileSchema"
            StringEquals: 'undefined'
            Next: MoveFileToUnStructuredRepo
          Default: MoveFileToStructuredRepo
        MoveFileToStructuredRepo:
          Type: Task
          Resource: moveFileToStructuredRepo
          Next: Done
        MoveFileToUnStructuredRepo:
          Type: Task
          Resource: moveFileToUnStructuredRepo
          Next: Done
        Done:
          Type: Task
          Resource: stepReport
          End: true

    step-consolidate:
      StartAt: Done
      States:
        Done:
          Type: Task
          Resource: startCrawler
          End: true



resources:
  Resources:
    S3BucketAssests:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.prefix.bucket.${self:provider.stage}}this-service-asset
    S3BucketSubmit:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.prefix.bucket.${self:provider.stage}}this-service-submit
        LifecycleConfiguration:
          Rules:
          - Id: GlacierRule
            Status: Enabled
            Transitions:
              - TransitionInDays: '1'
                StorageClass: Glacier
    SubmitStepLambdaPermissionSubmitS3:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - SubmitLambdaFunction
            - Arn
        Principal: "s3.amazonaws.com"
        Action: "lambda:InvokeFunction"
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: "arn:aws:s3:::${self:custom.prefix.bucket.${self:provider.stage}}this-service-submit"


plugins:
  - serverless-step-functions
  - serverless-s3-remover
  - serverless-finch


custom:
  defaultStage: dev
  profiles:
    dev: dev-profile
    pro: pro-profile
  regions:
    dev: us-east-2
    pro: us-east-1
  remover:
     buckets:
       - ${self:custom.prefix.bucket.${self:provider.stage}}this-service-submit
       - ${self:custom.prefix.bucket.${self:provider.stage}}this-service-validate
       - ${self:custom.prefix.bucket.${self:provider.stage}}this-service-asset
       - ${self:custom.prefix.bucket.${self:provider.stage}}this-service-consolidate
  client:
    bucketName: ${self:custom.prefix.bucket.${self:provider.stage}}this-service-asset
    distributionFolder: config
  prefix:
    function: ${self:service}-${opt:stage, self:custom.defaultStage}
    bucket:
      dev: dev-
      pro: pro-
```

**Comment by GuidoS** [comment]
Sadly, I do not have the time to make a simpler service as I am not using the variables to manage this at the moment.

**Comment by horike37** [comment]
Thank you for pinging @GuidoS :smile: 

The Plugin Version you reported is 0.3.0, which is the old one very much.
Currently, the latest version is 1.4.0. Please update it.
Additionally, the syntax of stepfunctions section in serverless.yml was slightly updated in v1.0 or later, so you should update those as well. Please make sure the details on README.

**Comment by GuidoS** [comment]
I updated the plugin and tested with the serverless.yml that follows. This seemed to work, so I will close this for now. Thank you @horike37 for helping me with this process.

```yml
service: upload-to-s3-and-postprocess

custom:
  defaultStage: alpha
  profiles:
    alpha: alpha-profile
    beta: beta-profile
  comment:
    alpha: "this is a alpha thing"
    beta: "this is a beta thing"

provider:
  name: aws
  runtime: nodejs6.10

  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  hello:
    handler: handler.hello

stepFunctions:
  stateMachines:
    yourParallelMachine:
      definition:
        Comment: ${self:custom.comment.${self:provider.stage}}
        StartAt: Parallel
        States:
          Parallel:
            Type: Parallel
            Next: Final State
            Branches:
            - StartAt: Wait 20s
              States:
                Wait 20s:
                  Type: Wait
                  Seconds: 20
                  End: true
            - StartAt: Pass
              States:
                Pass:
                  Type: Pass
                  Next: Wait 10s
                Wait 10s:
                  Type: Wait
                  Seconds: 10
                  End: true
          Final State:
            Type: Pass
            End: true
plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
```
