### ISSUE TITLE
Version 1.4.1 breaks pseudo parameters

### ISSUE THREAD

**Issue by jquatier** [horike37/serverless-step-functions#119]
# This is a Bug Report

## Description

The most recent version of this plugin breaks the functionality of using serverless-pseudo-parameters (https://www.npmjs.com/package/serverless-pseudo-parameters)

```
Serverless Error ---------------------------------------

  Invalid variable reference syntax for variable AWS::Region. You can only reference env vars, options, & files. You can check our docs for more info.
```
Note: Rolling back to 1.4.0 deploys successfully.

Configuration:
```
stepFunctions:
  stateMachines:
    myStateMachine:
      definition:
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:firstState"
            Next: NextState
```

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.23.0
* ***The Plugin Version you're using***: 1.4.1
* ***Operating System***: Mac OSX / Ubuntu
