### ISSUE TITLE
Consider not deriving logicalId from custom name.

### ISSUE THREAD

**Issue by dougmoscrop** [horike37/serverless-step-functions#123]
# This is a both a Bug Report and a Feature Proposal

The guidance posted in https://github.com/horike37/serverless-step-functions/issues/78 and in the README does not, as far as I can tell, actually work.

Given a service named `foo` and a deployment to `dev` stage of a state machine called myStateMachine:

> name: myStateMachine-${self:service}-${opt:stage}

becomes, e.g. `MyStateMachine-foo-dev` in YML, then `MyStateMachineDashFooDashDev` in compiled template.

> Ref: MyStateMachineDash${self:service}Dash${opt:stage}

Becomes `MyStateMachineDashfooDashdev`

`Foo` vs `foo` and `Dev` vs `dev`

I don't see any reason why the "name" property needs to determine the logicalId. It makes sense to only derive the logicalId from the key in the `stateMachines:` object, e.g.

```yml

stepFunctions:
  stateMachines:
    myStateMachine: # pass this through the normalization function, make it the logical id, maybe make sure it endsWith StateMachine
       name: ${self:service}-my-state-machine-${opt:stage} # this is just the AWS name, nothing to do with CF template, don't touch it/change it
```
