### ISSUE TITLE
Bug Report/Feature: Plugin fails silently

### ISSUE THREAD

**Issue by AnthonyWC** [horike37/serverless-step-functions#126]
Currently with this plugin it appears to fail silently; as serverless does not show any error but there was no step function created.

**Comment by mysteron** [comment]
Having the same issue. Any ideas what happens?

**Comment by horike37** [comment]
Hi @AnthonyWC @mysteron 
Could you share contents of your serverless.yml file so that we can take a look more deeply?

**Comment by AnthonyWC** [comment]
My current serverless.yml content changed a lot since then but I think back then was also using the alias plugin, if I recall I ran into issues IAM and/or calling wrong arn resource (e.g.. non-alias) for lambda in the step functoin.

Here's the serverless that I have now but before I also had alias plugin:
```
functions:
  - ${file(./lambda-functions.yml)}

stepFunctions: ${file(./state-machine.yml)}

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "${self:service}-${self:provider.stage}"

plugins:
  - serverless-plugin-tracing
  - serverless-step-functions
  - serverless-pseudo-parameters
```
