### ISSUE TITLE
Variables are not being replaced

### ISSUE THREAD

**Issue by paulopontesm** [horike37/serverless-step-functions#13]
Variables replaced. So something like this dosent work:
```
stepFunctions:
  hellostepfunc:
    Comment: "A Hello World example of the Amazon States Language using an AWS External Lambda Function"
    StartAt: HelloWorld
    States: 
      HelloWorld: 
        Type: Task
        Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountid}:function:external_hello_lambda_function
        End: true
```
