### ISSUE TITLE
Specify the stateMachine ARN to environment variables

### ISSUE THREAD

**Issue by joakync** [horike37/serverless-step-functions#135]
# This is a Bug Report

## Description
Hi
I tried to follow the official serverless [documentation](https://serverless.com/blog/how-to-manage-your-aws-step-functions-with-serverless/) and the [Readme](https://github.com/horike37/serverless-step-functions#how-to-specify-the-statemachine-arn-to-environment-variables) of this project regarding the assignment of the ARN dynamically to an ENV variable  but i always get the same error:

> The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [Mystatemachine] in the Resources block of the template

I tried with simple names and having in mind the first uppercase character with no luck

What i am trying to achieve is a HTTP event that triggers a lambda that validates the request and triggers a new Task using the SDK, but i need the ARN of the stateMachine generated dynamically.

```
service: stepfunctions-test-node

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - "*"

package:
  exclude:
    - '*'
    - '**'
  include:
    - handler.js


functions:
  ValidateRequest:
    handler: handler.validateRequest
    events:
      - http:
          path: pdf
          method: GET
    environment:
      statemachine_arn: ${self:resources.Outputs.Mystatemachine.Value}

stepFunctions:
  stateMachines:
    Mystatemachine:
      definition:
        Comment: Generates a printable on the fly voucher
        name: mystatemachine
        StartAt: ValidateRequest
        States:
          ValidateRequest:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-ValidateRequest
            Next: nextFunction
          .......


resources:
  Outputs:
    Mystatemachine:
      Value:
        Ref: Mystatemachine

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
```

## Additional Data
* serverless 1.28
* serverless-step-functions 1.5
* OSX
* Node v8.11.3
