### ISSUE TITLE
ApiGateway ApiKeys are not working

### ISSUE THREAD

**Issue by marcelalburg** [horike37/serverless-step-functions#137]
# This is a Bug Report

## Description
when i set the apiKeys property inside provider, the plugin will create the keys but they are not applied to the Gateway.

For bug reports:
* What went wrong?
ApiKey created, but not applied / working at the Gateway
* What did you expect should have happened?
I need this ApiKey to access the Apigateway
* What was the config you used?
```
provider:
  name: aws
  apiKeys:
    - ${self:service}-${opt:stage, self:provider.stage}
```
