### ISSUE TITLE
Bug in ApiGateway Template: apostrophe results in parsing error

### ISSUE THREAD

**Issue by marcelalburg** [horike37/serverless-step-functions#140]
# This is a Bug Report

It looks like in the stepfunctions api gateway template is the same error as here:  https://github.com/serverless/serverless/pull/2993/files

## Description
If an ' (apostrophe) inside the request, it will always fail. 

For bug reports:
* What went wrong?
JSON parsing wrong.
* What did you expect should have happened?
A valid JSON must be accepted and redirected to the StepFunction
* What was the config you used?
```
    ApiGatewayCall:
      name: ${self:service}-${opt:stage, self:provider.stage}-ApiGatewayCall
      timeout: 100 # optional, in seconds, default is 6

      events:
        - http:
            path: import
            method: POST
```
* What stacktrace or error message from your provider did you see?
`{"__type":"com.amazon.coral.service#SerializationException"}`

* ***Provider Error messages***:
```
curl -D - -XPOST -H "Content-Type: application/json; charset=utf-8" https://<endpoint>/dev/import -d "{\"name\":\"Palatto d'Inv\"}"
HTTP/2 400
content-type: application/json
content-length: 60
date: Sun, 05 Aug 2018 19:59:20 GMT
x-amzn-requestid: 0afcd14b-98ea-11e8-ad05-8f443798b4c1
x-amz-apigw-id: LKqL4HhyliAFoYQ=
x-amzn-trace-id: Root=1-5b675718-08e0041dcc5f96d971896ced
x-cache: Error from cloudfront
via: 1.1 affe26bf02a36a4a45ea1eb3ce2b4a62.cloudfront.net (CloudFront)
x-amz-cf-id: 7wbWVgMmsFwHFIFXhJ8S204WSsP2VGDUaRMZngL1nylrr50TqXZP7Q==

{"__type":"com.amazon.coral.service#SerializationException"}
```
