### ISSUE TITLE
choice "type" in step-functions workflow

### ISSUE THREAD

**Issue by anilktalla** [horike37/serverless-step-functions#15]
I was playing around with serverless-step-functions and I did not find a way to configure "choice" as part of the workflow. 

To accomplish something like below.
"CheckInventory": {
      "Type" : "Choice",
      "Choices": [
        {
          "Variable": "$.inventoryExists",
          "BooleanEquals": true,
          "Next": "ProcessOrder"
        },
        {
          "Variable": "$.inventoryExists",
          "BooleanEquals": false,
          "Next": "DeclineOrderBranch"
        }
      ]
    }

**Comment by horike37** [comment]
@anilktalla 
Thank you for using the plugin!! 
I think that it can be done as follow, how is it?

```yaml
stepFunctions:
  choicestepfunc:
    Comment: "Choice example"
    StartAt: CheckInventory
    States: 
      CheckInventory: 
        Type: Choice
        Choices:
          - Variable: "$.inventoryExists"
            BooleanEquals: true
            Next: ProcessOrder
          - Variable: "$.inventoryExists"
            BooleanEquals: false
            Next: DeclineOrderBranch
```
