### ISSUE TITLE
Get path parameters from API Gateway

### ISSUE THREAD

**Issue by johnleoclaudio** [horike37/serverless-step-functions#162]
How can I pass the _**user_id**_ as the initial input to the step function?

```
stepFunctions:
  stateMachines:
    hellostepfunc:
      name: HelloStep
      events:
        - http:
            path: notes/{user_id}
            method: GET
            cors: true
            authorizer: aws_iam
      input: {
        user_id: "$.user_id"
      }
```
