### ISSUE TITLE
Add support for optional name parameter

### ISSUE THREAD

**Issue by brynjagr** [horike37/serverless-step-functions#17]
Would be nice if you could add support for an optional name property.
E.g.:
```
stepFunctions:
  stateMachines:
    - name: myMachineName
      MyMachine:
         <description>
```

I would prefer to name the step function dynamically in order reference it from within a lambda that starts executing it, instead of having to hardcode the name into the lambda

Great job with the plugin btw 👍

**Comment by brynjagr** [comment]
As far as I know there is no way of "initiating" a step function based on an event, except from setting up a lambda that takes in an event and starts executing the step function.

In order to configure this using serverless I have added an environment variable to the "initiator" lambda that contains the ARN of the step function. Since there seemingly is no way of referencing a specific state machine I have to "hard code" the name of the stat machine into the environment variable:

```
functions:
  initiator:
    environment: 
      STEP_FUNCTION_ARN: arn:aws:states:eu-west-1:<MY ACCOUNT>:stateMachine:${self:service}-${self:custom.stage}-myStateMachine

stepFunctions:
  stateMachines:
    myStateMachine:
       ...
```
Not sure if this makes any sense at all, but it would be cool if one could reference a state machine somehow. Either by name or by making it possible getting the ARN directly by using the name of the machine – similar to how you can use names to refer to functions from a state machine.

I believe this is pretty much the same thing as @melquic asks for in #18.
