### ISSUE TITLE
Alarms: Make treating of missing data configurable

### ISSUE THREAD

**Issue by mastertinner** [horike37/serverless-step-functions#170]
# This is a Feature Proposal

## Description

The alarms go to `INSUFFICIENT_DATA` if the respective state machine doesn't run at least once a minute. I think that should be configurable because for most use cases, the state machine doesn't run on a set schedule and even if so, it won't run every minute.

I'd like to be able to configure how the alarms treat missing data either as `missing` (current implementation and AWS default) or as `ignore` (so it wouldn't move the alarms to `INSUFFICIENT_DATA` if the state machine doesn't run) or even allow to specify all options AWS allows here.

More information can be found in the [official AWS documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-and-missing-data).

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.37.0
* ***The Plugin Version you're using***: 1.12.0
* ***Operating System***: MacOS 10.14.3

**Comment by theburningmonk** [comment]
Good call 👍

**Comment by theburningmonk** [comment]
I'm thinking something along the lines of
```
alarms:
    topics:
        ok: arn:aws:sns:us-east-1:1234567890:NotifyMe
        alarm: arn:aws:sns:us-east-1:1234567890:NotifyMe
        insufficientData: arn:aws:sns:us-east-1:1234567890:NotifyMe
    metrics:
        - executionsTimeOut
        - executionsFailed
        - executionsAborted
        - executionThrottled
    treatMissingData: <missing (default) | ignore | breaching | notBreaching>
```

sounds good?

**Comment by theburningmonk** [comment]
or maybe give you the option to override individual alarms as well? e.g.
```
alarms:
    topics:
        ok: arn:aws:sns:us-east-1:1234567890:NotifyMe
        alarm: arn:aws:sns:us-east-1:1234567890:NotifyMe
        insufficientData: arn:aws:sns:us-east-1:1234567890:NotifyMe
    metrics:
        - executionsTimeOut
        - executionsFailed
        - executionsAborted
        - metric: executionThrottled
           treatMissingData: breaching # this alarm would use a different configuration
    treatMissingData: ignore # all alarms would use this unless stated otherwise
```
