### ISSUE TITLE
GetAtt intrinsic function support?

### ISSUE THREAD

**Issue by you-fail-me** [horike37/serverless-step-functions#178]
Readme currently suggests using pseudo parameters to interpolate arn strings in resource definitions, e.g.:
```
          HelloWorld1:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello
            End: true
```
Which is not too readable and is a bit clunky. Is it possible to use `!GetAtt` fn to reference lambda function arns from the state machine definition? E.g.:
```
          HelloWorld1:
            Type: Task
            Resource: !GetAtt MyLambdaFunction.Arn
            End: true
```
?
I've tried the option above and keep getting `state.Resource.startsWith is not a function`
