### ISSUE TITLE
Add support to start a step function execution from a Lambda function

### ISSUE THREAD

**Issue by melquic** [horike37/serverless-step-functions#18]
Hi,
Would be great if we could start a step function execution using the name defined in the serverless.yml file instead of the ARN.

Thank you.

**Comment by horike37** [comment]
Thank you for the reporting @melquic !
You can directly define the name of function in serverless.yaml.

Example as follow. Defined `hellofunc` functions can define in `Resource` statement.
```yaml
functions:
  hellofunc:
    handler: handler.hello

stepFunctions:
  stateMachines:
    hellostepfunc:
      Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
      StartAt: HelloWorld
      States: 
        HelloWorld: 
          Type: Task
          Resource: hellofunc
          End: true
``` 

Please try it again.
