### ISSUE TITLE
Support Global Tagging

### ISSUE THREAD

**Issue by dearmond** [horike37/serverless-step-functions#182]
# This is a Feature Proposal

## Description

For feature proposals:
* Global tags declared in Serverless should propagate to step functions as well.

Global defined like so:
```
provider:
  name: aws
  tags:
    foo: bar
    baz: qux
```

Similar or dependent issues:
* #166 Added tagging (awesome!) but not global tagging.

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.39.1
* ***The Plugin Version you're using***: 1.15.0
* ***Operating System***: macOS
