### ISSUE TITLE
make stepFunctions variable an array

### ISSUE THREAD

**Issue by MicMonen** [horike37/serverless-step-functions#184]
I have multiple Step-Functions inside one project. For readability I want to split them up in several files, but that doesn't seem possible now.

What I have now and works:
```
...
stepFunctions:
  stateMachines: ${file(./serverless/step-functions.yml)}
```

What I want but doesn't work:
```
...
stepFunctions:
  - stateMachines: ${file(./serverless/step-function/first.yml)}
  - stateMachines: ${file(./serverless/step-function/second.yml)}
```

**Comment by theburningmonk** [comment]
You can still have:
```
stepFunctions:
  stateMachines:
    first: ${file(first.yml)}
    second: ${file(second.yml)}
```
I have a more complete example on #177. 

Why would an array be better in this case?
