### ISSUE TITLE
Synchronous state machine execution from API Gateway event

### ISSUE THREAD

**Issue by andrhamm** [horike37/serverless-step-functions#195]
# This is a Feature Proposal

## Description

> What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Start a state machine execution from an API Gateway event but wait for the execution to complete in order to return the results in the API Gateway response, as opposed to starting the execution and returning the execution ARN while execution takes place asynchronously.

> If there is additional config how would it look

```yml
stepFunctions:
  stateMachines:
    hello:
      events:
        - http:
            path: hello
            method: GET
            awaitExecution: true
      definition:
```

## Additional Data

This could be accomplished by having the plugin automatically create a Lambda function that starts a state machine execution (`sartExecution`) and polls `describeExecution` for the execution `status` and `output`. The API Gateway event would map HTTP event to this Lambda directly instead of directly invoking the state machine. The Lambda would receive the target state machine ARN and, optionally, an execution name. In this way, the same Lambda could handle all such state machine configurations, assuming the IAM role could automatically be altered to allow `states:StartExecution`/`states:DescribeExecution` on only the applicable state machines.
