### ISSUE TITLE
Lambda ARN missing from IAM Role

### ISSUE THREAD

**Issue by levegetarien** [horike37/serverless-step-functions#201]
# This is a (Bug Report / Feature Proposal)

## Description

When implementing [Callbacks](https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-wait-token) in step functions, the IAM policy that gets generated does not include the ARN of the Lambda (Task).

The step function looks like this:

```
  name: some-name
  definition:
    Comment: "some step with callback"
    StartAt: request-approval
    States:
      request-approval:
        Type: Task
        Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
        Parameters:
          FunctionName: arn:aws:lambda:${self:provider.region}:${self:custom.stage.infra.AWS_ACCOUNT}:function:function-name-1
          Payload:
            token.$: "$$.Task.Token"
        End: true
```
The IAM policy that gets generated does contain all ARN of other lambdas included in the step, but not when using the ARN nested in the `Parameters` field. The resulting policy (and role) won't allow the step to invoke the lambda.

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.41.1
* ***The Plugin Version you're using***: 1.20.0
