### ISSUE TITLE
Template error: every value of the context object of every Fn::Sub object must be a string or a function that returns a string

### ISSUE THREAD

**Issue by gau1991** [horike37/serverless-step-functions#203]
# This is a Bug Report

## Description

Recently we upgraded version from v1.17.1 to v1.20, and we started getting following error:
```
╰─ sls deploy -s dev -r us-west-2
Serverless: Generated requirements from /abc/requirements.txt in /abc/.serverless/requirements.txt...
Serverless: Installing requirements from /abc/.serverless/requirements/requirements.txt ...
Serverless: Running ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service abc.zip file to S3 (10.76 MB)...
Serverless: Validating template...

  Error --------------------------------------------------

  The CloudFormation template is invalid: Template error: every value of the context object of every Fn::Sub object must be a string or a function that returns a string

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           12.3.1
     Serverless Version:     1.40.0
```

For bug reports:
* What went wrong? Serverless failed to verify cloudformation template
* What did you expect should have happened? Serverless shpuld to verify cloudformation template

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.40.0
* ***The Plugin Version you're using***: 1.20.0
* ***Operating System***: MacOS 10.14.5

**Comment by theburningmonk** [comment]
@gau1991 can you put your state machine definition here so I can use it to reproduce the issue?

**Comment by gau1991** [comment]
@theburningmonk 

here is the template:

```
stepFunctions:
  stateMachines:
    myStateMachines:
      definition:
        StartAt: One
        States:
          One:
            Type: Wait
            SecondsPath: 10
            Next: RefreshLead
          RefreshLead:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-lambda
            TimeoutSeconds: 60
            Next: EndState
          EndState:
            Type: Succeed
```

Funny thing here if state has name `RefreshLead` then only we are getting issue. This was working fine for 1.17.1 version.
