### ISSUE TITLE
Choice Support with Boolean

### ISSUE THREAD

**Issue by selvendranayyaswamy** [horike37/serverless-step-functions#217]
Need to understand a better way to deploy AWS Step functions with Multiple 'OR' conditions in Choice state. Something similar to this

"ChoiceStateX": {
  "Type": "Choice",
  "Choices": [
    {
        "Not": {
          "Variable": "$.type",
          "StringEquals": "Private"
        },
        "Next": "Public"
    },
    {
      "Variable": "$.value",
      "NumericEquals": 0,
      "Next": "ValueIsZero"
    },
    {
      "And": [
        {
          "Variable": "$.value",
          "NumericGreaterThanEquals": 20
        },
        {
          "Variable": "$.value",
          "NumericLessThan": 30
        }
      ],
      "Next": "ValueInTwenties"
    }
  ],
  "Default": "DefaultState"
},

**Comment by theburningmonk** [comment]
@selvendranayyaswamy can you put the code into a code block, e.g.
```
"ChoiceStateX": {
  "Type": ...
}
```
so it's easier to follow?

Also, I'm not sure what your question is. Are you asking for help to make this state machine more readable?

**Comment by selvendranayyaswamy** [comment]
Hi, 
Here is my requirement. I have step function with list of choice states. Basically I need to execute a lambda based on an OR condition. Here it is 

If the vehicleState is Edit or NewInterface, then we need to transition the step function to invoke a lambda. I know that we can have individual choices like this. So the current implementation that i have looks like this.
CheckRDRStatus:
            Type: Choice
            Choices:
            - Variable: "$.rdrStatus"
              StringEquals: "Edit"
              Next: UpdateOrchestrator
            - Variable: "$.rdrStatus"
              StringEquals: "NewInterface"
              Next: UpdateOrchestrator
            - Variable: "$.rdrStatus"
              StringEquals: "Queued"
              Next: TransmitRDR
            - Variable: "$.rdrStatus"
              StringEquals: "Pending"
              Next: WaitOnPublishRDRMessage

If you see the above code snippet, both Edit and NewInterface is calling the same step UpdateOrchestrator. I have two more choice values which also needs invoke the same UpdateOrchestrator step. I dont find any documentation on how to get this implemented, though I see an error message stating OR is a valid keyword.

**Comment by theburningmonk** [comment]
@selvendranayyaswamy have a look at the choice state section of the language spec [here](https://states-language.net/spec.html#choice-state). Looks like there is an `OR` operator, which should do what you want.

![image](https://user-images.githubusercontent.com/546969/59470316-37a9e900-8e2f-11e9-94f5-3d70e6ffc5eb.png)

**Comment by selvendranayyaswamy** [comment]
Can u send me a snippet on how to put that on serverless.yaml?

**Comment by theburningmonk** [comment]
something like this should do:

```yml
StartAt: ChoiceState
States:
  ChoiceState:
    Type: Choice
    Choices:
    - Or:
      - Variable: "$.foo"
        NumericEquals: 1
      - Variable: "$.foo"
        NumericEquals: 2
      Next: FirstMatchState
    Default: DefaultState
  FirstMatchState:
    Type: Task
    Resource: arn:aws:lambda:REGION:ACCOUNT_ID:function:OnFirstMatch
    End: true
  DefaultState:
    Type: Fail
    Error: DefaultStateError
    Cause: No Matches!
```
