### ISSUE TITLE
CW alarms created from stateMachines contain multipe "Dash" in alarm name

### ISSUE THREAD

**Issue by airmonitor** [horike37/serverless-step-functions#225]
# This is a (Bug Report / Feature Proposal)

Very long CW alarm, contain "Dash" instead of "-". Alarm was created from stateMachines.

> IoTAutomation-prd-IoTAutomationDashprdDashIoTAutomationExecutionsFailedAlarm-DKXRCQPR5LVQ

- What did you expect should have happened?

> IoTAutomation-prd-IoTAutomation-prd-IoTAutomationExecutionsFailedAlarm-DKXRCQPR5LVQ

- What was the config you used?
```
stepFunctions:
  stateMachines:
    IoTAutomation:
      alarms:
        topics:
          ok: ${self:provider.sns_cloudwatch_alarm_topic}
          alarm: ${self:provider.sns_cloudwatch_alarm_topic}
          insufficientData: ${self:provider.sns_cloudwatch_alarm_topic}
        metrics:
          - executionsFailed
```

- What stacktrace or error message from your provider did you see?
There is no stack trace

Similar or dependent issues:

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.46.1
* ***The Plugin Version you're using***:Linux Mint 19.1
* ***Operating System***:^2.0.0
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by theburningmonk** [comment]
@airmonitor unfortunately, this is because CloudFormation doesn't allow `-` in the names. Which is why the serverless framework would rename all function names with `-` in the name (e.g. `hello-world`) with the word `Dash` as well (e.g. `HelloDashWorldLambdaFunction`).

**Comment by airmonitor** [comment]
Auch :/

Can it be then removed completely from Alarm name, ie without "Dash"?
I was hitting the maximum limit of 64 characters in the CW Alarm name due to multiple "Dash" in its name :(

**Comment by theburningmonk** [comment]
Ok, I think the better approach here is to add an option to override the logical name. e.g. 

```yml
metrics:
    - metric: executionThrottled
      logicalName: MyAlarm # overrides the auto-generated resource name
      treatMissingData: breaching
```

**Comment by airmonitor** [comment]
Sadly something is not working for me:

```State machine [InfluxGrafanaAutomation-prd-IoTAutomation] : alarms config is malformed. Please see https://github.com/horike37/serverless-step-functions for examples. ValidationError: child "metrics" fails because ["metrics" at position 0 fails because ["0" must be a string, "logicalName" is not allowed]]
```

```
        metrics:
          - metric: executionsTimeOut
            logicalName: IoTAutomationexecutionsTimeOut
            treatMissingData: ignore
```
