### ISSUE TITLE
Intrinsic functions refering to a SNS topic failing

### ISSUE THREAD

**Issue by jmaralc** [horike37/serverless-step-functions#234]
# This is a Bug report

## Description
Not sure whether this is an issue or that I am not using in the proper-way the intrinsic functions with the workflow execution events. 
The situation is like this: 
I have a SNS topic defined in a yml like:
`Resources:
  DimModelerTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: SNS for issues regarding the step functions and modeling of read models
        TopicName: DimModelerTopic
`
end in the yml where I define the state machine I have at the bottom: 

notifications:
  ABORTED:
    - sns:
      Ref: DimModelerTopic

What I want to do is to refer to that topic and create an event that notifies me for ABORTED situations. 

For bug reports:
* What went wrong?
I have got this in the console:

State machine [ZeepDimensionModeler] : notifications config is malformed. Please see https://github.com/horike37/serverless-step-functions for examples. ValidationError: child "ABORTED" fails because ["ABORTED" at position 0 fails because [child "sns" fails because ["sns" must be a string, "sns" must be an object, "sns" must be an object]]]

And the cloudwatch event is not created.

I put a console.log in the line 313 of the compileNotification.js and I got:
{ ABORTED: [ { sns: null, Ref: 'DimModelerTopic' } ] }

* What did you expect should have happened?
I expected no errors and that the event in cloudwatch was created and linked to the state machine. 
The only way I managed this working was: 
using this:
  ABORTED:
    - sns: { 'Fn::Join': [':', ['arn:aws:sns', { Ref: 'AWS::Region' },{Ref: 'AWS::AccountId'},{ 'Fn::GetAtt': ['DimModelerTopic', 'TopicName'] }]] }

and skipping the validateConfig function. But I think there should be a proper way of doing it that I am not seeing.

* What was the config you used?
Serverless version 1.47.0
Plus these pluggins:
  - serverless-plugin-split-stacks
  - serverless-layers
  - serverless-python-requirements
  - serverless-step-functions
  - serverless-pseudo-parameters

* What stack trace or error message from your provider did you see?
Mentioned above.

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.47.0
* ***The Plugin Version you're using***: v2.1.0
* ***Operating System ***: macOS
* ***Stack Trace***:
* ***Provider Error messages***: State machine [ZeepDimensionModeler] : notifications config is malformed. Please see https://github.com/horike37/serverless-step-functions for examples. ValidationError: child "ABORTED" fails because ["ABORTED" at position 0 fails because [child "sns" fails because ["sns" must be a string, "sns" must be an object, "sns" must be an object]]]

**Comment by theburningmonk** [comment]
I just tested this on v2.1.0 (but not using any of the other plugins you had), and it worked for me:

```
stepFunctions:
  stateMachines:
    snsExample:
      name: sns-example
      definition:
        Comment: Demonstrate how the SNS integration works
        StartAt: Publish SNS message
        States:
          Publish SNS message:
            Type: Task
            Resource: arn:aws:states:::sns:publish
            Parameters:
              Message: "{ \"answer\": 42 }"
              TopicArn:
                Ref: AlarmTopic
              MessageAttributes:
                foo:
                  DataType: String
                  StringValue: bar
            End: true
      notifications:
        ABORTED:
          - sns:
              Ref: AlarmTopic
```

could it be something silly like indentation (gets me all the time!)? failing that, could you try removing the other plugins and see if it's a compatibility issue with another plugin?
