### ISSUE TITLE
Create one IAM role per function

### ISSUE THREAD

**Issue by theburningmonk** [horike37/serverless-step-functions#249]
# This is a Feature Proposal

## Description

Now that you can have nested workflows, the one IAM role for all is becoming a recurring problem.

E.g. if you have something like the following:

```
stepFunctions:
  stateMachines:
    root:
      definition:
        StartAt: Call nested
        States:
          Call nested:
            Type: Task
            Resource: arn:aws:states:::states:startExecution
            Parameters:  
              Input: "42"                
              StateMachineArn:
                Ref: Nested
              Name: $$.Execution.Id
            End: true
    nested:
      id: Nested
      definition: ...
```
Now we have a circular dependency... root depends on IAM role, which depends on the `Nested` state machine through `Ref`, but the `Nested` state machine also depends on the IAM role.

So far, I've only managed to work around this by setting the `StateMachineArn` with a string (using the `serverless-pseudo-parameters` plugin to help construct the ARN.
