### ISSUE TITLE
StartExecution of statemachines through API Gateway

### ISSUE THREAD

**Issue by msl-kabo** [horike37/serverless-step-functions#25]
It would be really good to have the ability to start execution of a statemachine by calling a url.

https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-api-gateway.html

Suggestion for how it could look in `serverless.yml`

```yaml
stepFunctions:
  stateMachines:
    myStateMachine:
      events:
        - http:
          method: GET
          path: executeMyStateMachine
```
