### ISSUE TITLE
Support Map State

### ISSUE THREAD

**Issue by billyshambrook** [horike37/serverless-step-functions#257]
# This is a Bug Report

## Description

When using this plugin with the new Map state, the state machine IAM role does not include the functions listed under `Iterator:`

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.52.1
* ***The Plugin Version you're using***: 2.7.0

**Comment by jamaica474** [comment]
Map state still doesn't work. As far as I can see it ignores content of "Iterator" key.

Relevant part of config:
`deliverBatch:
      name: deliverBatchPipeline-${opt:stage}
      definition:
        Comment: "Delivers batch of postings"
        StartAt: LOCK_POSTINGS
        States:
          LOCK_POSTINGS:
            Type: Map
            Iterator:
              StartAt: MARK_POSTING_AS_PROCESSED
              States:
                MARK_POSTING_AS_PROCESSED:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [markProcessed, Arn]
                  End: true
            End: true`

Error: `
 ✕ State machine "deliverBatch" definition is invalid:
  [{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/fail#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/pass#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/succeed#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/task#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/wait#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"oneOf","dataPath":".States['LOCK_POSTINGS']","schemaPath":"#/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"}]`

**Comment by dobeerman7** [comment]
I've tried to use your plugin, bit it fails at `Map` state. 
Probably, I've missed something important, but I've double checked it already.

Here my definition of state machine:

```yaml
stepFunctions:
  stateMachines:
    whatsAppStateMachine:
      name: whatsAppStateMachine-{$self:provider.stage}
      events:
        - http:
            path: whatsapp/message
            method: post
      definition:
        StartAt: MessageDetection
        States:
          MessageDetection:
            Type: "Task"
            InputPath: "$"
            Resource:
              Fn::GetAtt: [messageDetection, Arn]
            OutputPath: "$"
            Next: HandleAgentMessage
          HandleAgentMessage:
            Type: "Task"
            InputPath: "$"
            Resource:
              Fn::GetAtt: [handleAgentMessage, Arn]
            OutputPath: "$"
            Next: SendAgentMessageToWhatsApp
          SendAgentMessageToWhatsApp:
            Type: "Map"
            InputPath: "$"
            ItemsPath: "$.Messages"
            MaxConcurrency: 0
            Parameters:
              - "Message.$": "$$.Map.Item.Value"
              - "Secrets.$": "$.Secrets"
            Iterator:
              StartAt: SendAgentMessage,
              States:
                SendAgentMessage:
                  Type: "Task"
                  Resource:
                    Fn::GetAtt: [sendAgentMessage, Arn]
                  End: true
            ResultPath: "$.MessagesSent"
            End: true
  validate: true
```

I've got the following errors:

```json
[
  {
    "keyword": "additionalProperties",
    "dataPath": ".States['SendAgentMessageToWhatsApp']",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "ItemsPath"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": ".States['SendAgentMessageToWhatsApp']",
    "schemaPath": "http://asl-validator.cloud/fail#/additionalProperties",
    "params": {
      "additionalProperty": "ItemsPath"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": ".States['SendAgentMessageToWhatsApp']",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "ItemsPath"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": ".States['SendAgentMessageToWhatsApp']",
    "schemaPath": "http://asl-validator.cloud/pass#/additionalProperties",
    "params": {
      "additionalProperty": "ItemsPath"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": ".States['SendAgentMessageToWhatsApp']",
    "schemaPath": "http://asl-validator.cloud/succeed#/additionalProperties",
    "params": {
      "additionalProperty": "InputPath"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": ".States['SendAgentMessageToWhatsApp']",
    "schemaPath": "http://asl-validator.cloud/task#/additionalProperties",
    "params": {
      "additionalProperty": "ItemsPath"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": ".States['SendAgentMessageToWhatsApp']",
    "schemaPath": "http://asl-validator.cloud/wait#/additionalProperties",
    "params": {
      "additionalProperty": "ItemsPath"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "type",
    "dataPath": ".States['SendAgentMessageToWhatsApp'].Parameters",
    "schemaPath": "#/properties/Parameters/type",
    "params": {
      "type": "object"
    },
    "message": "should be object"
  },
  {
    "keyword": "oneOf",
    "dataPath": ".States['SendAgentMessageToWhatsApp']",
    "schemaPath": "#/oneOf",
    "params": {
      "passingSchemas": null
    },
    "message": "should match exactly one schema in oneOf"
  },
  {
    "Error code": "MISSING_TRANSITION_TARGET",
    "Message": "State SendAgentMessage is not reachable"
  },
  {
    "Error code": "MISSING_TRANSITION_TARGET",
    "Message": "Missing 'StartAt'|'Next'|'Default' target: SendAgentMessage,"
  }
]
```

Could you help me to figure out what happens?
Thanks!
