### ISSUE TITLE
YAML integers being converted to strings when declaring CW events

### ISSUE THREAD

**Issue by TheBishopOfSoho** [horike37/serverless-step-functions#260]
# This is a Bug Report

## Description
When creating a cloudwatch Event for triggering execution of a state machine, for some reason the Step Functions plugin is converting numbers to strings. e.g. My State machine is defined like so:
```
stepFunctions:
  stateMachines:
    fooFunction:
      name: fooFunction
      definition:
        ${file(step_functions/foo.yml)}    
      events:
        - cloudwatchEvent:
            event:
              source:
                - 'aws.medialive'
              detail-type:
                - 'MediaLive Channel State Change'
              detail:
                state:
                  - 'RUNNING'
                pipelines_running_count: [2]
```
When I deploy this, the event in CW is defined like so:
```
{
  "detail-type": [
    "MediaLive Channel State Change"
  ],
  "source": [
    "aws.medialive"
  ],
  "detail": {
    "pipelines_running_count": [
      "2"
    ]    
  }
}
```
I cant see why the array for pipelines_running_count would get converted to a string, and I dont think this is something I am doing wrong, Im following the YAML spec for this. 
Any ideas why this is happening?

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.53
* ***The Plugin Version you're using***: Latest
* ***Operating System***: Ubuntu 18.04.2
