### ISSUE TITLE
CloudFormation intrinsics are not replaced in string arrays

### ISSUE THREAD

**Issue by staticfinal** [horike37/serverless-step-functions#267]
# This is a Bug Report

## Description

I'm using the Step Functions service integration to start a task on Fargate. I need a custom network configuration which references a security group. I use a CloudFormation `Ref` to reference the security group. When I try to deploy the stack I get an error from CloudFromation:

`'SCHEMA_VALIDATION_FAILED: The value for the field 'null' must be a STRING at /States/.../Parameters`

Using a CloudFormation `Ref` to reference a cluster in the parameters works though.

This is the configuration:

```
stepFunctions:
  stateMachines:
    processFile:
      definition:
        States:
          RunTask:
            Type: Task
            Resource: "arn:aws:states:::ecs:runTask.waitForTaskToken"
            Parameters:
              LaunchType: "FARGATE"
              Cluster:
                Ref: ActivityCluster
              ...  
              NetworkConfiguration:
                AwsvpcConfiguration:
                  AssignPublicIp: "ENABLED"
                  SecurityGroups:
                  - Ref: ActivitySecurityGroup
                  Subnets:
                  - Ref: ActivitySubnet
            ...        
            Next: NextTask
...
resources:
  Resources:
    ActivityCluster:
      Type: "AWS::ECS::Cluster"
      Properties:
        ClusterName: "Activities-${opt:stage, self:provider.stage}"
    ActivitySecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: "Generated by #{AWS::StackName}"
...
```

The generated CloudFormation template looks like this:

```
    "ProcessFileStateMachineDashdev": {
      "Type": "AWS::StepFunctions::StateMachine",
      "Properties": {
        "DefinitionString": {
          "Fn::Sub": [
            "... \"Cluster\": \"${ShqxHdxkFb}\" ... \"SecurityGroups\": [{ \"Ref\": \"ActivitySecurityGroup\" }]",
            {
              "ShqxHdxkFb": {
                "Ref": "ActivityCluster"
              },
          ]}       
```

So the intrinsics are correctly converted to a string replacement if the occur in an object but not if they occur in a string array.

## Additional Data
* Serverless: 1.47.0
* serverless-step-functions: 2.10.0
* macOS 10.14.6
