### ISSUE TITLE
IamRoleStateMachineExecution policy fails legacy parsing

### ISSUE THREAD

**Issue by kabo** [horike37/serverless-step-functions#269]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
My step function didn't get deployed
* What did you expect should have happened?
My step function to be deployed
* What was the config you used?
```yaml
          Transform:
            Type: Task
            InputPath: "$.transformInput"
            ResultPath: "$.transformResult"
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:#{TransformLambdaFunction}"
            Next: WriteToBi
          WriteToBi:
            Type: Task
            InputPath: "$.writeInput"
            ResultPath: "$.writeResult"
            Resource: "${self:custom.config.flow.bi.resourceArn}"
            Next: GoToEnd
```
* What stacktrace or error message from your provider did you see?
```
  An error occurred: IamRoleStateMachineExecution - The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: ea77d411-4f63-4266-9d88-e559b8556bc4).
 ```

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.54.0
* ***The Plugin Version you're using***: 2.10.1
Here's what `.serverless/cloudformation-template-update-stack.json` looks like:
```json
    "IamRoleStateMachineExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "states.eu-west-1.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "test-eu-west-1-academedia-termkatalog-to-bi-statemachine",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "lambda:InvokeFunction"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${TransformLambdaFunction}"
                    },
                    {
                      "Fn::Sub": [
                        "${functionArn}:*",
                        {
                          "functionArn": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${TransformLambdaFunction}"
                        }
                      ]
                    },
                    "arn:aws:lambda:eu-west-1:XXX:function:YYY",
                    {
                      "Fn::Sub": [
                        "${functionArn}:*",
                        {
                          "functionArn": "arn:aws:lambda:eu-west-1:XXX:function:YYY"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          }
        ]
      }
    },

```
