### ISSUE TITLE
Feature Request: Nested workflow

### ISSUE THREAD

**Issue by hideokamoto** [horike37/serverless-step-functions#273]
# This is a Feature Proposal
We want to create a nested workflow by the plugin.

## Expected
We want to create a nested workflow like this.

```yaml
stepFunctions:
  stateMachines:
    ChildStateMachine:
      definition:
        Comment: "Child state machine"
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource:
              Fn::GetAtt: [map, Arn]
            End: true
    ParentStateMachine:
      definition:
        Comment: "Parent state machine"
        StartAt: HelloKids
        States:
          HelloKids:
            Type: Task
            Resource:
              Fn::GetAtt: [map, Arn]
            Next: CallKids
          CallKids:
            Type: Task
            Resource: "arn:aws:states:::states:startExecution.sync"
            Parameters:
              StateMachineArn:
                Fn::GetAtt: [ChildStateMachine, Arn]
              Input:
                AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: "$$.Execution.Id"
            End: true
```

## Actual
But we get a following error.

```
$ sls deploy
 Error --------------------------------------------------
 
  Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource FirstStateMachine
      at provider.request.catch.error (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:19:13)
      at tryCatcher (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:696:18)
      at tryOnImmediate (timers.js:667:5)
      at processImmediate (timers.js:649:5)
      at process.topLevelDomainCallback (domain.js:121:23)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.5.0
     Framework Version:         1.54.0
     Plugin Version:            3.1.2
     SDK Version:               2.1.2
     Components Core Version:   1.1.1
     Components CLI Version:    1.2.3
```

## Additional info
When we change `Parameters.StateMachineArn` parameters like this, we get a another error message.

```yaml
          CallKids:
            Type: Task
            Resource: "arn:aws:states:::states:startExecution.sync"
            Parameters:
              StateMachineArn:
                Fn::GetAtt: [FirstStateMachineStepFunctionsStateMachine, Arn]
```

```

  Error --------------------------------------------------
 
  Error: The CloudFormation template is invalid: Circular dependency between resources: [IamRoleStateMachineExecution, YourCatchMachineStepFunctionsStateMachine, SecondStateMachineStepFunctionsStateMachine, FirstStateMachineStepFunctionsStateMachine]
      at provider.request.catch.error (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:19:13)
      at tryCatcher (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/Cellar/nvm/0.33.1/versions/node/v10.5.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:696:18)
      at tryOnImmediate (timers.js:667:5)
      at processImmediate (timers.js:649:5)
      at process.topLevelDomainCallback (domain.js:121:23)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.5.0
     Framework Version:         1.54.0
     Plugin Version:            3.1.2
     SDK Version:               2.1.2
     Components Core Version:   1.1.1
     Components CLI Version:    1.2.3
```

## Additional Data

```
     Operating System:          darwin
     Node Version:              10.5.0
     Framework Version:         1.54.0
     Plugin Version:            3.1.2
     SDK Version:               2.1.2
     Components Core Version:   1.1.1
     Components CLI Version:    1.2.3
```

**Comment by hideokamoto** [comment]
When we put the state machine ARN directory, it works.

```yaml
            Next: CallKids
          CallKids:
            Type: Task
            Resource: "arn:aws:states:::states:startExecution.sync"
            Parameters:
              StateMachineArn:
                "arn:aws:states:us-east-1:399999999:stateMachine:ChildStateMachineStepFunctionsStateMachine-xxxxxxx"
              Input:
                AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: "$$.Execution.Id"
            End: true
```

**Comment by theburningmonk** [comment]
For the first error, it's because the plugin creates a logical ID based on your state machine name `FirstStateMachine`, you can override the generated logical ID [like this](https://github.com/horike37/serverless-step-functions#adding-a-custom-logical-id-for-a-statemachine).

For the second error, it's because the plugin currently creates one IAM role for all state machines. #249 would fix this problem but I haven't got around to working on it yet.

**Comment by theburningmonk** [comment]
@hideokamoto can you try again against the latest v2.14.0? It now supports one IAM role per state machine and should fix the circular dependency you saw before

**Comment by hideokamoto** [comment]
Thanks!
I'll check it tomorrow!!

**Comment by hideokamoto** [comment]
It works!
Thank you the update 👍 🍺 🍺 🍺 🍺 

```yaml
stepFunctions:
  stateMachines:
    ParentStateMachine:
      definition:
        Comment: "Parent state machine"
        StartAt: HelloKids
        States:
          HelloKids:
            Type: Task
            Resource:
              Fn::GetAtt: [map, Arn]
            Next: CallKids
          CallKids:
            Type: Task
            Resource: "arn:aws:states:::states:startExecution.sync"
            Parameters:
              StateMachineArn:
                Ref: ChildStateMachineStepFunctionsStateMachine
              Input:
                AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: "$$.Execution.Id"
            End: true
    ChildStateMachine:
      definition:
        Comment: "Child state machine"
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource:
              Fn::GetAtt: [map, Arn]
            End: true
```
