### ISSUE TITLE
Step functions do not inherit global tags

### ISSUE THREAD

**Issue by psech** [horike37/serverless-step-functions#274]
# Bug Report

serverless@1.54.0

## Description

1. What did you do?
Provided `stackTags` under `provider` in serverless.yml. Like in [docs](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/)
1. What happened?
My step function has not been tagged
1. What should've happened?
My step function should have been tagged according to [docs](https://serverless.com/plugins/serverless-step-functions/#tags)

> You can specify tags on each state machine. Additionally, any global tags (specified under provider section in your serverless.yml) would be merged in as well.

1. What's the content of your `serverless.yml` file?
```
provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'ap-southeast-2'}
  stage: ${opt:stage, 'dev'}
  stackTags:
    Description: "Serverless Build of service: ${self:service}"
    Service: "${self:service}"
    Branch: "${opt:branchId, 'manual'}"
    Build: "${opt:buildId, 'manual'}"
    Template: None
    Environment: "${opt:stage}"
    Team: QA
...
stepFunctions:
  stateMachines:
    calculateQualityScore:
      name: ${self:provider.environment.STATE_MACHNE_NAME}
      definition:
        Comment: "Calculates QualityScore"
        StartAt: FetchBugs
        States:
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Notging significant, normal deployment

Similar or dependent issues: N/A

**Comment by theburningmonk** [comment]
@psech see the comments in #182 the `stackTags` don't get propagated to state machines unless it's a fresh deploy, that's a problem with CloudFormation. I've reported it to AWS several times, but until they fix it, the only workaround I know of is to use this SAR : https://github.com/lumigo-io/SAR-Propagate-CFN-Tags

But, if you use `tags` instead of `stackTags` then we will tag the state machine resource directly, and that'll be updated whenever you update the tags. `stackTags` adds the tags to the CloudFormation stack and defers to CloudFormation to propagate them to the resources in the stack, which right now has that problem of updates not being propagated to some resources I mentioned above.

**Comment by theburningmonk** [comment]
@psech I'm gonna close this for now, feel free to reopen if you have follow-up questions

**Comment by MrAtheist** [comment]
Hi @theburningmonk,

I'm getting the same problem here. I've added both `tags` and `stackTags` under `provider` just to make sure that all taggable actions are accounted for.

```
provider:
  name: aws
  runtime: nodejs12.x
  tracing:
    lambda: true
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  stackTags:
    App: ${self:custom.tagging.APP}
    Env: ${opt:stage, 'dev'}
    Owner: ${self:custom.tagging.OWNER}
    ...more tags
  tags: 
    App: ${self:custom.tagging.APP}
    Env: ${opt:stage, 'dev'}
    Owner: ${self:custom.tagging.OWNER}
    ...more tags

custom:
  tagging:
    APP: MyApp
    OWNER: ME 
    
```
- Heres the weird bit: the state machine is only tagged with `Owner` and nothing else, not sure whats the underlying magic thats skipping the other tags...
- stackTag` seems to be working and propagates **all** the tags to sub resources, except (as far as i can tell) the lambda role, which probably is due to the issue you've mentioned above.

Next, I went ahead and add `tags` directly within the state machine:

```
stepFunctions:
  stateMachines:
    MyStateMachine:
      name: MyStateMachine${self:provider.stage}
      tags:
        App: ${self:custom.tagging.APP}
        Env: ${self:provider.stage}
        Owner: ${self:custom.tagging.OWNER}
        .... more tags

# ...and this doesnt appear to be doing anything
```

Any other magic that i might have missed?

Running `serverless-step-functions@2.17.2`
