### ISSUE TITLE
Cloudformation stalls at creation of step function.

### ISSUE THREAD

**Issue by keithrozario** [horike37/serverless-step-functions#277]
# This is a Bug Report

## Description

Cloudformation stalls at creation of step function, when trying to deploy a stepfunction that tries to call another step function. In my `serverless.yml` file i have 3 step functions, one of which tries to call another using the sync method. That specific step function has issues deploying, and hangs!

For bug reports:

Cloudformation stalls when trying to deploy the following step function:
```yaml
    invoke:
      name: ${self:custom.pipelineName}-root_invoke
      definition:
        Comment: "Invoke the Check, Build and Deploy pipeline for all packages"
        StartAt: Invoke
        States:
          Invoke:
            Type: Task
            Resource: arn:aws:states:::states:startExecution.sync
            Parameters:
              Input:
                package: "requests"
              StateMachineArn: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:custom.pipelineName}
              Name: "Invoker"
            Next: Done
          Done:
            Type: Succeed
```

The cloudformation hangs at the creation of the step function (for hours!)

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.54.0
* ***The Plugin Version you're using***:  2.3.0
* ***Operating System***: MacOS
* ***Stack Trace***:
* ***Provider Error messages***: Hangs at `Create in Progress`
