### ISSUE TITLE
Error using environment variables (wrong type)

### ISSUE THREAD

**Issue by IPWright83** [horike37/serverless-step-functions#280]
I feel like I might be missing something obvious here, but here we go.

# Bug Report

## Description

For bug reports:
When trying to pull an environment variable for Seconds attribute in the Wait type of State the deploy command fails.

```
Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Expected value of type Integer at /States/WaitForCampusM/Seconds' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: 1facfbb9-9570-456d-8c33-1a2dadaea5ff).
```

I would expect this to have deployed succesfully. A hard-coded value works fine, if I echo out the environment variable I can see the value correctly.

![image](https://user-images.githubusercontent.com/1374775/70063278-671c0000-15df-11ea-9ecf-d4d167c6941b.png)

This is the interesting part of the bitbucket pipeline:
```
image: node:10.16.0

definitions:
    steps:
        - step: &deploy
              name: Deploy
              script:
                  - npm install -g serverless
                  - echo $CAMPUSM_WAIT_DELAY
                  - sls deploy
```

This is the interesting part of my serverless.yml
```
plugins:
    - serverless-step-functions
...
stepFunctions:
    stateMachines:
        my-sync:
            name: my-sync
            definition:
                StartAt: getStartTime
                States:
                    getStartTime:
                        Type: Task
                        Resource:
                            Fn::GetAtt: [getStartTime, Arn]
                        Next: MyTimetablePull
                    MyTimetablePull:
                        Type: Task
                        Resource:
                            Fn::GetAtt: [myTimetablePull, Arn]
                        Next: MyTimetablePushToRDS
                    MyTimetablePushToRDS:
                        Type: Task
                        Resource:
                            Fn::GetAtt: [myTimetablePushToRDS, Arn]
                        Next: WaitForCampusM
                    WaitForCampusM:
                        Type: Wait
                        Seconds: ${env:CAMPUSM_WAIT_DELAY}
                        Next: CampusMPull
                    CampusMPull:
                        Type: Task
                        Resource:
                            Fn::GetAtt: [campusMPull, Arn]
                        Next: CampusMPushToRDS
                    CampusMPushToRDS:
                        Type: Task
                        Resource:
                            Fn::GetAtt: [campusMPushToRDS, Arn]
                        End: true
```

## Additional Data
* ***Serverless Framework Core Version you're using***: (latest) 1.58.0
* ***The Plugin Version you're using***: (latest) 2.12.0
