### ISSUE TITLE
Support the new express workflow

### ISSUE THREAD

**Issue by theburningmonk** [horike37/serverless-step-functions#281]
# This is a Feature Proposal

## Description

Express workflow has been launched at re:invent, looking at CloudFormation [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html) it's added `StateMachineType` (defaults to `STANDARD`) and `LoggingConfiguration` (only valid for express workflows).

Probably we can have something along the lines of :

```yml
stepFunctions:
  stateMachines:
    sayHello:
      type: EXPRESS <-- optional, default to STANDARD
      loggingConfig:
        level: ALL | ERROR | FATAL | OFF <-- default to OFF
        includeExecutionData: true | false <-- defaults to false
        destinations:
          - cw log group arn
          - cw log group arn
      definition: ...
```
