### ISSUE TITLE
Blank tags property erroring in certain AWS regions

### ISSUE THREAD

**Issue by maafk** [horike37/serverless-step-functions#287]
# This is a Bug Fix (kind of) and a Feature Proposal

## Description

For bug reports:
* What went wrong?
  * Compiled Cloudformation failed due to [Tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-tags) not being supported for StateMachines in some regions
* What did you expect should have happened?
  * Should have left out the [`Tags`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-tags) property if not provided
* What was the config you used?
  * Standard config that would work just fine in `us-east-1`, but _without_ tags
* What stacktrace or error message from your provider did you see?
  * The Cloudformation error stating that [`Tags`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-tags) is not a valid property

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
  * If no tags are provided for a StateMachine, rather than add a `Tags` property with an [empty array](https://github.com/horike37/serverless-step-functions/blob/master/lib/deploy/stepFunctions/compileStateMachines.js#L210), don't include Tags at all. If Cloudformation in a specific region doesn't support Tags for a StateMachine, it will error even if provided an empty array
  * If a StateMachine has a property of `inheritGlobalTags` of `false`, _don't_ add the global tags to the specified state machine

* If there is additional config how would it look
  * For each StateMachine defined, add an optional boolean property of `inheritGlobalTags`

**I have a PR ready to address this issue**

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.59.2
* ***The Plugin Version you're using***: 2.12.0
* ***Operating System***: MacOS Catalina 10.15.2 
* ***Stack Trace***: 
* ***Provider Error messages***: Property 'Tags' not a valid property

**Comment by theburningmonk** [comment]
@maafk do you have an example of the state machine definition you used that gives you invalid CloudFormation?

**Comment by theburningmonk** [comment]
@maafk also, I'm curious, which regions don't support tags for State Machines?

**Comment by maafk** [comment]
> @maafk do you have an example of the state machine definition you used that gives you invalid CloudFormation?

At this point it's _any_ state machine deployed in a region where the [`AWS::StepFunctions::StateMachine`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.htm) resource doesn't support the [`Tags`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-tags) property.

```yaml
service: my-service

provider:
  name: aws
  runtime: python3.7
  region: mars-east-1 # see comment below on regions
  # no tags

functions:
  helloFunc:
    handler: handler.hello

stepFunctions:
  stateMachines:
    StateMachine1:
      name: my-neat-state-machine
      # no tags
      definition:
        StartAt: OnlyState
        States:
          OnlyState:
            Type: Task
            Resource:
              Fn::GetAtt: [helloFunc, Arn]
            End: true

plugins:
  - serverless-step-functions
```

> @maafk also, I'm curious, which regions don't support tags for State Machines?

There are non-public regions out there, as alluded to in the [serverless-private-aws-regions](https://github.com/maafk/serverless-private-aws-regions) plugin, with varying degrees of AWS services and features. Mostly _lacking_ features (such as tags for step functions).

The changes proposed in [PR 288](https://github.com/horike37/serverless-step-functions/pull/288) shouldn't affect users in regions with full Tags support (probably the vast majority of users), but would _greatly_ help a user base in some separate regions.

Currently we're either using only version [1.14.0](https://github.com/horike37/serverless-step-functions/releases/tag/v1.14.0) (tag support was introduced in [1.15.0](https://github.com/horike37/serverless-step-functions/compare/v1.14.0...v1.15.0)), or hacking the latest version to do something similar to [PR 288](https://github.com/horike37/serverless-step-functions/pull/288).

Thanks! 👍
