### ISSUE TITLE
EventBridge Support

### ISSUE THREAD

**Issue by TreeMan360** [horike37/serverless-step-functions#289]
Is it possible to trigger the step function with an EventBridge event? I have tried this but it does not execute.

```
stepFunctions:
  stateMachines:
    meetingReminders:
      events:
        - eventBridge:
            eventBus: ${self:custom.eventBus}
            pattern:
              source:
                - accounts
              detail-type:
                - meetingConfirmed
      definition:
        Comment: 'Waits and sends reminders to meeting participants'
        StartAt: GettingMeetingReminders
        States:
          GettingMeetingReminders:
            Type: Task
            Resource:
              Fn::GetAtt: [getMeetingReminders, Arn]
            Next: SendingMeetingReminders
          SendingMeetingReminders:
            Type: Map
            ItemsPath: $.reminders
            MaxConcurrency: 1
            Iterator:
              StartAt: WaitingToSend
              States:
                WaitingToSend:
                  Type: Wait
                  TimestampPath: $.sendAt
                  Next: Sending
                Sending:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [sendMeetingReminder, Arn]
                  End: true
            End: true
  validate: true
```

**Comment by TreeMan360** [comment]
I can't get this to work and I don't see any rules created in EventBridge that would cause the step-function to begin execution. The step function is created, and my other functions that are triggered on the EventBus are working correctly and with their rules created appropriately, but no rule is created to kick of the above state machine.

**Comment by TreeMan360** [comment]
If I create the EventBridge rule manually then it works fine, any suggestions on why the rule isn't being created automatically would be greatly appreciated.

**Comment by theburningmonk** [comment]
@TreeMan360 have a look at [this](https://github.com/horike37/serverless-step-functions#cloudwatch-event) part of the documentation, for the moment we only support CloudWatch Events. For what you're doing the two are interchangeable and the CW Event rules you create would show up in EventBridge too. The main caveat is that you can't use the name [content-based filters](https://www.tbray.org/ongoing/When/201x/2019/12/18/Content-based-filtering) with CW Events.

**Comment by theburningmonk** [comment]
@TreeMan360 looking at it more closely, both CloudWatch Events and EventBridge use the same CloudFormation resource type [AWS::Events::Rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html) so the two really are equivalent. So you can use the content-based filters (it's just not supported in the EventBridge console) with the current implementation already.

**Comment by TreeMan360** [comment]
@theburningmonk absolutely fabulous 🥳🎉😎

**Comment by TreeMan360** [comment]
I just tried this out and it does indeed work with the default bus. However, I am having issues using an ARN as the eventBusName. I have tried setting this as the eventBus property also but this seems to have no effect. When specifying eventBusName as an ARN I receive a validation error as I would anticipate for a "name".

I use an ARN rather than a name as I have an issue with serverless in that it throws an error stating the bus already exists if you use the name multiple times in a serverless.yml. Therefore right now I am creating the bus manually and using an ARN. I will see if this issue has been resolved but either way I would expect to be able to use an ARN or a Name so this has parity with the standard EventBus configuration.

Unless of course I am doing something wrong :)

```
  stateMachines:
    meetingReminders:
      events:
        - eventBridge:
            eventBusName: ${self:custom.eventBus}
            event:
              pattern:
                source:
                  - meetings
                detail-type:
                  - meetingConfirmed
      definition:
```
Results in:
```
An error occurred: MeetingRemindersEventsRuleCloudWatchEvent1 - 1 validation error detected: Value 'arn:aws:events:eu-west-1:790413216414:event-bus/8dc-dev' at 'eventBusName' failed to satisfy constraint: Member must satisfy regular expression pattern: [/\.\-_A-Za-z0-9]+ (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: e17b2556-1b4a-4aa3-a4fb-9dfd2d6bd596).
```

If I do the following:
```
  stateMachines:
    meetingReminders:
      events:
        - eventBridge:
            eventBus: ${self:custom.eventBus}
            event:
              pattern:
                source:
                  - meetings
                detail-type:
                  - meetingConfirmed
      definition:
```

Then the rule is deployed to the default bus and the eventBus property is ignored.

Merry Xmas and thanks for all your great work, much appreciated.

**Comment by theburningmonk** [comment]
Have a look at the document [here](https://github.com/horike37/serverless-step-functions#specifying-a-custom-cloudwatch-eventbus) on how to specify the bus name. It does need to be a name, not an ARN.

If you had created the bus by hand then you can use stick the name in there. But in the spirit of infrastructure-as-code you should create the bus via CloudFormation (in the `resources` section of your `serverless.yml`) and then `Ref` it. See [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html#aws-resource-events-eventbus-return-values).

**Comment by richardtapendium** [comment]
@TreeMan360 Did you manage to get this working? I'm having the same problem where no new rule is being created.

My config looks like so:

```
events:
        - cloudwatchEvent:
            eventBusName: tap-events-uat
            event:
              source:
                - "my.custom.source"
              detail-type:
                - "My Event Type"
              detail:
                state:
                  - pending
```

Thanks for the awesome library, and any help is much appreciated!
