### ISSUE TITLE
Getting TypeError: obj must be an Array or an Object as soon as I add plugin

### ISSUE THREAD

**Issue by duro** [horike37/serverless-step-functions#292]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Adding the plugin to my plugin list and then deploying, I get:

`TypeError: obj must be an Array or an Object`

* What did you expect should have happened?

Deploy should proceed

* What was the config you used?

I have tried both with and without a defined `stepFunctions` block. When I tried with a minimal `stepFunctions` block it looked like this:

```
stepFunctions:
  validate: true
  stateMachines:
    charger:
      definition:
        Comment: 'Workflow to charger partners for rides'
        StartsAt: GatherTrips
        States:
          GatherTrips:
            Type: Task
            Resource:
              Fn::GetAtt: [gatherTrips, Arn]
            End: true
```

* What stacktrace or error message from your provider did you see?

```
Type Error ---------------------------------------------

TypeError: obj must be an Array or an Object
    at /opt/app/node_modules/json-refs/index.js:1195:15
```

## Additional Data
* ***Serverless Framework Core Version you're using***:

1.59.3

* ***The Plugin Version you're using***:

2.15.0

* ***Operating System***:

linux
