### ISSUE TITLE
Redefine response Mapping template

### ISSUE THREAD

**Issue by dobeerman** [horike37/serverless-step-functions#295]
# This is a (Help needed)

## Description

For feature proposals:
* State machine execution should return a static object with some parameters

## Additional Data
* ***Framework Version: 1.60.1***:
* ***Plugin version: 2.16.0***:

I trying to change *response* template, but seems it doesn't works.
So, I've added the following lines to serverless.yml:
```yml
stepFunctions:
  stateMachines:
    myStateMachine:
      name: myStateMachine-${self:provider.stage}
      events:
        - http:
            path: mypath
            method: post
            response:
              template:
                application/json: |
                  {
                    "status": 200,
                    "info": "OK"
                  }
```

Is there any additional settings I have to add?
