### ISSUE TITLE
IamRoleStateMachineExecution with permissions boundary

### ISSUE THREAD

**Issue by jraj002** [horike37/serverless-step-functions#298]
# This is a (Bug Report / Feature Proposal)

## Description
Following code in my serverless.yml used to work, but I have started getting error messages after I upgraded my serverless & step functions version. Attached error messages.

```
resources:
  Resources:
    # Permission Boundary
    IamRoleStateMachineExecution:
      Properties:
        PermissionsBoundary: "arn:aws:iam::#{AWS::AccountId}:policy/LZ-IAM-Boundary"
    
    # Permission Boundary
    IamRoleLambdaExecution:
      Properties:
        PermissionsBoundary: "arn:aws:iam::#{AWS::AccountId}:policy/LZ-IAM-Boundary"

    # Permission Boundary
    IamRoleCustomResourcesLambdaExecution:
      Properties:
        PermissionsBoundary: "arn:aws:iam::#{AWS::AccountId}:policy/LZ-IAM-Boundary"        
```

## Additional Data
* ***Serverless Framework Core Version you're using***:
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.1.0
     Framework Version:         1.56.1
     Plugin Version:            3.2.1
     SDK Version:               2.1.2
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

* ***The Plugin Version you're using***:
* ***Operating System***:
MacOS 10.14.6

* ***Stack Trace***:
```
  Error: The CloudFormation template is invalid: Template format error: [/Resources/IamRoleStateMachineExecution] Every Resources object must contain a Type member.
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:126:23)
```
