### ISSUE TITLE
Specification with v1.0

### ISSUE THREAD

**Issue by horike37** [horike37/serverless-step-functions#31]
Hi everyone.
We discussed  about including the step functions feature into Serverless Core for a while.
However, We decided to postpone that finally. The reason for that we should decide how to manage a plovider specific feature(Serverless is multi-provider support)
See the detail: https://github.com/serverless/serverless/issues/3024

Therefore I will update the plugin to v1.0 and out of beta, based feedback I got.
Here is specification for v1.0. If you have any ideas, please comment here!

### serverless.yml 
```yaml
provider:
  name: aws
  runtime: nodejs4.3

functions:
  hellofunc:
    handler: handler.hello

stepFunctions:
  stateMachines:
    myStateMachine1:
      role: arn:aws:iam:::role/InsertYourFavoriteRoleNameHere #Optional, you can chose the existing IAM Role
      events: #Here is events for stepfunctions. You can define http, schedule and cloudwatchEvent.
        - http:
          method: GET
          path: executeMyStateMachine
        - schedule: rate(2 hours)
        - cloudwatchEvent:
          event:
            source:
              - "aws.ec2"
            detail-type:
              - "EC2 Instance State-change Notification"
            detail:
              state:
                - pending
      definition: #Required. Here is the Amazon States Language definition.
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld1
        States: 
          HelloWorld1:
            Type: Task
            Resource: [lambda name | activity name | lambda ARN | activity ARN | Fn::GetAtt (lambda) | Fn::Ref (activity) | Fn::ImportValue]
            End: true
  activities: #Here is Task activites
    - myTask
```

### deploy
Include this in `sls deploy` without adding new commands.

### invoke
Add `sls invoke --stepfunction <statemachin name>` option.  `-sf` is as short version.
