### ISSUE TITLE
ServerlessError: Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED 

### ISSUE THREAD

**Issue by rukshanchristy** [horike37/serverless-step-functions#36]
Hi I'm trying to get a simple Step Function to be mapped with http endpoint

```
stepFunctions:
  stateMachines:
    Issue2FAToken:
      events:
        - http:
            path: 2fa/step
            method: GET
      definition:
        Comment: "Issuing 2FA token to user via SMS"
        StartAt: CreateToken
        States:
          CreateToken:
            Type: Task
            Resource: createToken
            Next: SendToken
          SendToken:
            Type: Task
            Resource: sendToken
            End: true
```
I do get the following error. Ive checked the syntax against the examples in but cant figure out whats wrong

```
ServerlessError: Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED at , SCHEMA_VALIDATION_FAILED at , SCHEMA_VALIDATION_FAILED at '
    at provider.request.then.catch (/---/two-factor-authentication/node_modules/serverless-step-functions/lib/stateMachine.js:86:13)
From previous event:
    at ServerlessStepFunctions.createStateMachine (/---/two-factor-authentication/node_modules/serverless-step-functions/lib/stateMachine.js:79:11)
    at BbPromise.map (/---/two-factor-authentication/node_modules/serverless-step-functions/lib/stateMachine.js:97:36)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```
Appreciate any help that I could get to get this working. Thanks
