### ISSUE TITLE
Authorizer support for http event

### ISSUE THREAD

**Issue by horike37** [horike37/serverless-step-functions#38]

**Comment by maxlaberge** [comment]
Any "hacky" way to get this done for now?

**Comment by horike37** [comment]
The only "hacky" way is that you set up the authorizer with deployed API on the management console, but that's NOT the recommended way since it would break the concurrency of CloudFormation behind the scene

**Comment by maxlaberge** [comment]
Ok, thanks for the info! 

In that case, can we help you to get this done? Has some work been started in order for this to be possible? Right now this issue makes this entire plugin useless since we need authorizers on all our API calls.

Thanks again!

**Comment by horike37** [comment]
>In that case, can we help you to get this done? Has some work been started in order for this to be possible?
Thank you for the kind word @maxlaberge 👍 
Unfortunately, I haven't work on this yet, and I may not take time for the functionality for a couple of months.
It would be great if you implement that and send PR to the repo 👍 

Ah, I just notice the other smarter way, which uses the http event of the serverless core.
You can get the detail here. Hopefully, this would be some of the help you
https://serverless.com/blog/how-to-manage-your-aws-step-functions-with-serverless/#use-triggered-lambda-events

**Comment by maxlaberge** [comment]
Hi,

Thank you for the suggestion, it is a great solution actually! I will see if I can get the time to fix it on my side and create a PR.

Thanks again for everything!

**Comment by maxlaberge** [comment]
Hi @horike37 upon implementing the solution in your article, I have come to an issue here:

```
stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: myStateMachine
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld1
        States:
          HelloWorld1:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello"
            End: true
resources:
  Outputs:
    MyStateMachine:
      Description: The ARN of the example state machine
      Value:
        Ref: MyStateMachine
```

I get the following error:
Template format error: Unresolved resource dependencies [MyStateMachine] in the Resources block of the template

Would you know why?

Thanks!
