### ISSUE TITLE
Step function names have changed

### ISSUE THREAD

**Issue by justinmchase** [horike37/serverless-step-functions#40]
Example serverless file:
```
service: example
plugins:
  - serverless-step-functions # 1.0
stepFunctions:
  stateMachines:
    foo:
      definition: ...
```

**Expected**
The generated lambda should be named: `example-justin-foo`

**Actual**
The generated lambda is `FooStepFunctionsStateMachine-2C1XDD2NCZCR`

Is there any way to control the name so I can have what it was before? Specifically for my usecases it must have the stage in it, it must start with the service name and it cannot have randomness in the name.

**Comment by justinmchase** [comment]
It appears that I have to get the Arns of the state machines by using `Ref: Name...`. The problem I'm having is that referencing these arns from within the step function definitions themselves is not resolving the ref first. I need to setup some kind of dependency chain probably, I'll update here if I figure that out.

**Comment by horike37** [comment]
@justinmchase 
Thank you for the opening this issue! The cause that the deployment has became through CloudFromation. Unfortunately it can't directly specify the name of statemachine, so actually the name generated automatically by CF. But TBH I haven't thought that much about it yet to provide a better proposal.

I think that maybe resolve the problem by implementing global arn parser which is disscussed in the following issue
https://github.com/serverless/serverless/issues/3212

**Comment by justinmchase** [comment]
For posterity I think that the fix is something like this:
```
service: example
plugins:
  - serverless-step-functions

provider: ...

functions:
  # Fast, common functions
  step_executor:
    handler: handler.step_executor
    environment:
        example_arn: ${self:resources.Outputs.Example.Value} # The resolved arn

stepFunctions:
  stateMachines:
    Example:
      definition: ${file(example.yml)}

resources:
  Outputs:
      Example:
        Description: The ARN of the example state machine
        Value:
          Ref: ExampleStepFunctionsStateMachine # resolves the step function arn by ref
```
