### ISSUE TITLE
Provided ARN for resourse is invalid

### ISSUE THREAD

**Issue by kararade** [horike37/serverless-step-functions#41]
hey guys!

I'm getting an error with the following data using the plugin after start the state machine
`{"error":"States.Runtime","cause":"An error occurred while scheduling the state 'CreatePhotoDocument'. The provided ARN 'create' is invalid."}
`

<img width="1573" alt="screen shot 2017-04-19 at 16 26 24" src="https://cloud.githubusercontent.com/assets/6010411/25201541/1b7ad2c8-2520-11e7-9796-5ea0b16fb511.png">

This is part of my YML file
```
    provider:
      iamRoleStatements:
        - Effect: Allow
          Action:
            - states:*
          Resource: "*"

    functions:
      create:
        handler: handler.create
      resize:
        handler: handler.resize

    stepFunctions:
      stateMachines:
        photoResizeWatermark:
          events:
            - http:
                path: ''
                method: POST
                cors: true
          definition:
            StartAt: CreatePhotoDocument
            States:
              CreatePhotoDocument:
                Type: Task
                Resource: create
                Next: ResizeThumbAndPreview
              ResizeThumbAndPreview:
                Type: Task
                Resource: resize
                End: true
```

could you give me a hand on this please?

Thanks
