### ISSUE TITLE
Support Fn::Join for resource ARN

### ISSUE THREAD

**Issue by jjasonclark** [horike37/serverless-step-functions#46]
Other parts of the `serverless.yml` file can be configured to use the `Fn::Join` syntax to pull out the ARN for a resource.  Can the plugin support the following syntax?

```
Resource:
  Fn::Join:
    - ":"
    - - arn
      - aws
      - lambda
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - function
      - ${self:service}-${opt:stage}-myFunction
```
