### ISSUE TITLE
Cloudwatch schedule events are not created

### ISSUE THREAD

**Issue by jjasonclark** [horike37/serverless-step-functions#48]
The Cloudwatch schedule events are not being created when deploying. Manual creation works. (aka seems its an allowed action)

```
stepFunctions:
  stateMachines:
    myMachine:
      events:
        - schedule: rate(5 minutes)
      definition:
        StartAt: MyStart
        States:
          MyStart:
            Type: Task
            Resource: "arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${opt:stage}-myFunction"
            End: true
```
