### ISSUE TITLE
Can not get the stateMachine Arn as the environment virables

### ISSUE THREAD

**Issue by KathyTian** [horike37/serverless-step-functions#52]
Hi, 
I have followed the tutorial in the end of the README and I'm trying to get the stateMachine's arn. However, there seems a error:
**Template format error: Unresolved resource dependencies
[MyStateMachine] in the Resources block of the template**

Could you help me to figure it out? I just followed the same code as the tutorial.

**Comment by horike37** [comment]
Thank you for the report @KathyTian !
Could you give me your serverless.yml? I'd like to try to reproduce it.

**Comment by KathyTian** [comment]
Thank you for your reply @horike37 !!
The serverless.yml is as below:
```
service: stepFunction
frameworkVersion: ">=1.1.0 <2.0.0"
description: This service is designed to convert original dope to step function

provider:
  name: aws
  tableName: my-table-step
  runtime: nodejs6.10
  region: us-east-1
  accountId: 844578468727
  timeout: 20
  iamRoleStatements:
    # - Effect: Allow
    #   Action:
    #     - lambda:AWSLambdaBasicExecutionRole
    #     - lambda:AWSStepFunctionsFullAccess
    #   Resource: "arn:aws:lambda:${opt:region, self:provider.region}:*:function:${self:service}-${opt:stage}-initStepFunction"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.tableName}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.tableName}/index/IdempotencyIdRequestIdIndex"

# The `functions` block defines what code to deploy
functions:
  initStepFunction:
    handler: handler.initStepFunction
    description: Init the step function for adding the authorizer
    timeout: 20
    environment:
      statemachine_arn: ${self:resources.Outputs.MyStateMachine.Value}
    events:
      - http:
          method: POST
          path: initStepFunction
          authorizer: authorizer
          cors: true
  calculate_dope_step:
    handler: handler.calculate_dope_step
    description: Provide DOPE based formular calculation API for (a+b)/(c-d)
    timeout: 20
  generateFinalResponse:
    handler: handler.generateFinalResponse
    description: Output the result of the equation
    timeout: 20
  plus:
    handler: calculation.plus
    description: Add the two numbers (a+b)
    timeout: 20
  subtract:
    handler: calculation.subtract
    description: subtract the two numbers (c-d)
    timeout: 20
  divide:
    handler: calculation.divide
    description: divide the result from the parallel
    timeout: 20
  authorizer:
    handler: handler.authorizer
    description: An authorizer for the http request

stepFunctions:
  stateMachines:
    MyStateMachine:
      name: MyStateMachine
      # events:
      #   - http:
      #       method: POST
      #       path: calculate_dope_step
      #       authorizer: authorizer
      #       cors: true
      definition:
        Comment: "An example of translating the prototype into step functions"
        StartAt: InputParameters
        States:
          InputParameters:
            Type: Task
            Resource: arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.accountId}:function:${self:service}-${opt:stage}-calculate_dope_step
            Next: choiceState
          choiceState:
              Type: Choice
              Choices:
              - Variable: "$.Item.getRequestByIdempotencyId"
                StringEquals: 'True'
                Next: generateFinalResponse
              - Variable: "$.Item.getRequestByIdempotencyId"
                StringEquals: 'False'
                Next: parallel
              Default: defaultState
          generateFinalResponse:
            Type: Task
            Resource: arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.accountId}:function:${self:service}-${opt:stage}-generateFinalResponse
            End: true
          parallel:
            Type: Parallel
            Next: divide
            Branches:
            - StartAt: plus
              States:
                plus:
                  Type: Task
                  Resource: arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.accountId}:function:${self:service}-${opt:stage}-plus
                  Next: choiceStatePlus
                choiceStatePlus:
                  Type: Choice
                  Choices:
                  - Variable: "$.Item.plus"
                    NumericEquals: 0
                    Next: success
                  Default: defaultPlus
                success:
                  Type: Succeed
                defaultPlus:
                  Type: Pass
                  End: true
            - StartAt: subtract
              States:
                subtract:
                  Type: Task
                  Resource: arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.accountId}:function:${self:service}-${opt:stage}-subtract
                  Next: choiceStateSubtract
                choiceStateSubtract:
                  Type: Choice
                  Choices:
                  - Variable: "$.Item.subtract"
                    NumericEquals: 0
                    Next: fail
                  Default: defaultSubtract
                fail:
                  Type: Fail
                  Cause: "The subtract number is 0"
                defaultSubtract:
                  Type: Pass
                  End: true
          divide:
            Type: Task
            Resource: arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.accountId}:function:${self:service}-${opt:stage}-divide
            Next: generateFinalResponse
          defaultState:
            Type: Fail
            Cause: "No matches"
resources:
  Outputs:
    MyStateMachine:
      Description: The ARN of the example state machine
      Value:
        Ref: MyStateMachine
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: my-table-step
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          -
            AttributeName: request_id
            AttributeType: S
          -
            AttributeName: idempotency_id
            AttributeType: S
          -
            AttributeName: created
            AttributeType: N
        KeySchema:
          -
            AttributeName: request_id
            KeyType: HASH
          -
            AttributeName: created
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: IdempotencyIdRequestIdIndex
            KeySchema:
              -
                AttributeName: idempotency_id
                KeyType: HASH
              -
                AttributeName: created
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
plugins:
  - serverless-step-functions

```

**Comment by KathyTian** [comment]
@horike37 . Thank you again for your reply. Actually, I was trying to add the authorizer function. If I use the API gateway as below to trigger the step function, it seems that the authorizer doesn't work.
```
 events:
         - http:
             method: POST
             path: calculate_dope_step
             authorizer: authorizer
             cors: true
```
So I tried to use API gateway to trigger the lambda function and use this lambda function to trigger step function. So i need the state machine ARN. However, it seems that it failed again and the serverless file is as above.

Therefore, do you have other solutions about adding the authorizer function and is there anything wrong with my method? 

Thank you for your assistance.
