### ISSUE TITLE
Custom name not working

### ISSUE THREAD

**Issue by kjprice** [horike37/serverless-step-functions#53]
I'm very excited to be able to use a custom name! I just gave it a go and am getting an error.

> The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [Hellostepfunc1StepFunctionsStateMachine] in the Resources block of the template

It appears that the step function is getting created with correct name, but the resource is being referenced using the old, compiled name.

Here is an example of the serverless.yml that will cause the issue:

```yml

service: step-functions
custom:
  accountId: xxxxxxxx
plugins:
  - serverless-step-functions
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hellofunc:
    handler: handler.hello
stepFunctions:
  stateMachines:
    hellostepfunc1:
      events:
        - http:
            path: api/track
            method: post
      name: myStateMachine
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld1
        States:
          HelloWorld1:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${opt:stage}-hello
            End: true
```

Thanks!

Using Version 1.0.3
