### ISSUE TITLE
Since 1.0.3 no more cf step is generated

### ISSUE THREAD

**Issue by fmuracciole** [horike37/serverless-step-functions#57]
When i upgrade to 1.0.3/1.0.4, the plugin has stopped generating the step function. The definition hasn't changed, find here an extract :

```
stepFunctions:
  stateMachines:
    fullIndex:
      name: myStateMachine
      role: arn:aws:iam::${self:custom.${opt:stage}.accountId}:role/service-role/StatesExecutionRole-${opt:region} 
      events:
        - http:
            path: /admin/trigger-full-index
            method: GET
      definition:
        Comment: ""
        StartAt: FullIndex
        States:
          FullIndex:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.${opt:stage}.accountId}:function:service-${opt:stage}-FullIndex
            Next: DeleteIndexes
          DeleteIndexes:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.${opt:stage}.accountId}:function:service-${opt:stage}-DeleteIndexes        
            End: true
```

Have you an idea ?
How to see the logs ?

**Comment by robizz** [comment]
me too +1

**Comment by anrocox** [comment]
The same happens to me, the plugin works in the generation of CloudFormation until version 1.0.2.

**Comment by horike37** [comment]
@fmuracciole 
Thank you for openning this issue.
Did you face the same problem on v1.0.4? I have fixed the bug that http event wasn't deployed when updating v 1.0.3 to v1.0.4.

If you can not run the plugin on v 1.0.4, Could you please give me your all of serverless.yml? and Did you see some kind of error when deploying? If so, Clould you give me the error message?

**Comment by fmuracciole** [comment]
Hello Horike,

Thanks for your reply,

 

Unfortunenately i can’t give you the rest of the config (confidentiality clause), @all somebody can give his config ?

I’ve test the both versions 1.0.3 and 1.0.4, and nothing is generated.

 

No error message is given, even in the aws console, because the cf is empty (no step description, no endpoint)

Regards,

 

De : Takahiro Horike [mailto:notifications@github.com] 
Envoyé : lundi 3 juillet 2017 04:54
À : horike37/serverless-step-functions <serverless-step-functions@noreply.github.com>
Cc : fmuracciole <frederic.muracciole@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [horike37/serverless-step-functions] Since 1.0.3 no more cf step is generated (#57)

 

@fmuracciole <https://github.com/fmuracciole> 
Thank you for openning this issue.
Did you face the same problem on v1.0.4? I have fixed the bug that http event wasn't deployed when updating v 1.0.3 to v1.0.4.

If you can not run the plugin on v 1.0.4, Could you please give me your all of serverless.yml? and Did you see some kind of error when deploying? If so, Clould you give me the error message?

**Comment by horike37** [comment]
Umm.. I made a slight similar one based on serverless.yml that is given by @fmuracciole and tried again. However, worked fine. Can someone provide me with serverless.yml to reproduce this problem?

Here is my serverless.yml.

```yml
service: sls-test-test

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 10

stepFunctions:
  stateMachines:
    fullIndex:
      name: myStateMachine
      role: arn:aws:iam::<here is account ID>:role/service-role/StatesExecutionRole-${opt:region}
      events:
        - http:
            path: /admin/trigger-full-index
            method: GET
      definition:
        Comment: ""
        StartAt: FullIndex
        States:
          FullIndex:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:<here is account ID>:function:${self:service}-${opt:stage}-hello
            Next: DeleteIndexes
          DeleteIndexes:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:<here is account ID>:function:${self:service}-${opt:stage}-hello
            End: true

plugins:
  - serverless-step-functions

```
