### ISSUE TITLE
Name is getting changed

### ISSUE THREAD

**Issue by FelschR** [horike37/serverless-step-functions#58]
I set a custom name "ProcessImage-s3" to my step function.
Now it turns out the created function is actually named "ProcessImageDashs3".

I noticed this because I tried refererncing the step function using `${self:resources.Outputs.processImageStepFunction.Value}` and I got the following error:
```
The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ProcessImage-s3] in the Resources block of the template
```

**Comment by lima02** [comment]
same here... not sure how to reference it from my starter lambda function. This is my scenario:
`S3 file upload => lambda "starter" function => step function`
I am using a lambda function just to start a step function off of an S3 event.

**Comment by horike37** [comment]
@FelschR 
Thank you for oppening this issue!
Could you please give me your using the Framework version and the plugin version?
Then Could you please also show me your serverless.yml?

**Comment by FelschR** [comment]
I'm using serverless 1.16.1 and serverless-step-functions 1.0.4.
My serverless.yml is quite big and I'd have to go over it before I can post it here.
But it basically comes down to the following:

```yml
custom:
  config: ${file(./config.yml)}

[...]

  processImage:
    handler: build/src/processImage.handler
    memorySize: 128
    timeout: 10
    environment:
      StateMachineArn: ${self:resources.Outputs.processImageStepFunction.Value}

[...]

stepFunctions:
  stateMachines:
    processImageStepFunction:
      name: ${self:custom.config.imageProcessStepFunctionName}
      definition:
        [...]

[...]

resources:
  Outputs:
    processImageStepFunction:
      Description: The ARN of the state machine
      Value:
        Ref: ${self:custom.config.imageProcessStepFunctionName}
```

In my `config.yml` I have:
```yml
imageProcessStepFunctionName: ProcessImage-s3
```

The environment variable I set for the lambda function had an incorrect value.

**Comment by horike37** [comment]
@FelschR 
I have re-written your serverless.yml, and deployed successfully on my laptop.
Here is:

```yml
custom:
  config: ${file(./config.yml)}

functions:
  processImage:
    handler: handler.hello
    memorySize: 128
    timeout: 10
    environment:
      StateMachineArn: ${self:resources.Outputs.ProcessImageS3.Value}

stepFunctions:
  stateMachines:
    processImageStepFunction:
      name: ${self:custom.config.imageProcessStepFunctionName}
      definition:
        [...]

resources:
  Outputs:
    ProcessImageS3:
      Description: The ARN of the state machine
      Value:
        Ref: ${self:custom.config.imageProcessStepFunctionName}
```
Here is also `config.yml`:

```yml
imageProcessStepFunctionName: ProcessImageS3
```

Please try again.

Note:
Named `ProcessImage-s3` can not use in Outputs section since non alphanumeric, so rename `ProcessImageS3`.
