### ISSUE TITLE
Choice Steps

### ISSUE THREAD

**Issue by rdehnhardt** [horike37/serverless-step-functions#60]
How can I create choice states?

I'm using this way:
```
States:
    Task1:
      Type: Task
      Resource: arn:aws:lambda:...
      Next: ChoiceState
    
    ChoiceState:
      Type: Choice
      Choices:
        - Variable: $.var
          NumericEquals: 0
          Next: Task2
          
        - Variable: $.var
          NumericEquals: 1
          End: true

    Task2:
      Type: Task
      Resource: arn:aws:lambda:...
      End: true
```
