### ISSUE TITLE
Choice statements not working

### ISSUE THREAD

**Issue by biznickman** [horike37/serverless-step-functions#65]
I've tried to implement a Choice statement but it fails to deploy. However if I convert to JSON and put it in the step functions visual interface it works perfectly. Here's the specific statement that causes it to break:

```
SubscriberCheckState:
    Type: Choice
    Choices:
        - Variable: "$.subscribed"
           BooleanEquals: true
           Next: UpdateAirtableEmailRecord
        - Variable: "$.subscribed"
           BooleanEquals: false
           End: true
```

No matter how I attempt to format the statement, it breaks. As soon as I remove it, everything functions properly. I've tested adding a Default statement and removing the quotes from variable but nothing works. The error that I get is:

`- Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED
     at /SubscriberCheckState/Choices/1, SCHEMA_VALIDATION_FAILED`

**Comment by gpsamson** [comment]
@biznickman It might be the spacing.

Try this:
```
          SubscriberCheckState:
            Type: Choice
            Choices:
            - Variable: "$.subscribed"
              BooleanEquals: true
              Next: UpdateAirtableEmailRecord
            - Variable: "$.subscribed"
              BooleanEquals: false
              End: true
```

That's using 2 spaces for tabs and the choices are parallel to "Choices:". I believe I had an error similar to yours and proper spacing fixed it.
