### ISSUE TITLE
Get Step Machine ARN through Lambda (Custom name)

### ISSUE THREAD

**Issue by Clement-mMedia** [horike37/serverless-step-functions#69]
Hi all
Firstly good job for this Awesome Serverless plugin and mostly for the complete README documentation.

Since few days I've been trying to define a custom name to my Step Machine.
This machine can be created with a custom dynamic name but I can't retrieve the ARN of this Step Machine via a lambda function.

Like explained into the **README.md**, i've tried to define an Output entry into my serverless.yml
But Cloud Formation rejects my request.

**serverless.yml**
``` yaml
...
stepFunctions:
  stateMachines:

    MyStateMachine:
      name: MyStateMachine-${self:service}-${opt:stage}
      definition:
...
resources:
  Outputs:
    MyStateMachine:
      Description: The ARN of the example state machine
      Value:
        Ref: MyStateMachine
...
```

**Error returned :** 
``` shell
Unresolved resource dependencies [MyStateMachine] in the Outputs block of the template
```

I also have tried this Output, but doesn't work

``` yaml
...
resources:
  Outputs:
    MyStateMachine:
      Description: The ARN of the example state machine
      Value: { "Fn::GetAtt": ["MyStateMachine", "Name"] }
...
```

**Error returned :** 
``` shell
Template error: instance of Fn::GetAtt references undefined resource MyStateMachine
```

Best regards

**Comment by iamsniffles** [comment]
Me as well ☹️

**Comment by horike37** [comment]
Thank you for opening up the issue @Clement-mMedia !
I am taking a look into this. Please give me a little time

**Comment by ChenLi0830** [comment]
The following config works for me. 
```
functions:
  hello:
    handler: handler.hello
    environment:
      statemachine_arn: ${self:resources.Outputs.MyStateMachine.Value}
  end:
    handler: handler.end

stepFunctions:
  stateMachines:
    helloWaitMachine:
      name: MyStateMachine
      definition:
        Comment: "An example of the Amazon States Language using wait states"
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${opt:stage}-hello
            Next: wait_using_seconds
          wait_using_seconds:
            Type: Wait
            Seconds: 1
            Next: FinalState
          FinalState:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${opt:stage}-end
            End: true


resources:
  Outputs:
    MyStateMachine:
      Description: The ARN of the example state machine
      Value:
        Fn::GetAtt: [ "MyStateMachine", "Name"]
```
Namely, I can get the state machine ARN through `const stateMachineName = process.env.statemachine_arn;`

However, I can't seem to find a way to invoke the step function through CLI. 
I tried both the followings: 
`sls invoke stepf --name helloWaitMachine`
`sls invoke stepf --name MyStateMachine`
