### ISSUE TITLE
How to access to event headers?

### ISSUE THREAD

**Issue by lorengordon** [horike37/serverless-step-functions#73]
# This is a Bug Report (I think)

## Description

I am attempting to respond to a GitHub webhook that is configured with a secret that I use to authenticate the event. The basic code is the [aws-node-github-webhook-listener](https://github.com/serverless/examples/tree/master/aws-node-github-webhook-listener) example project. But I'd like to use a step function to receive the webhook and control the execution flow from there.

If I use the serverless.yml from the example and trigger the webhook, everything works fine. However, if I setup the template to use serverless-step-functions, it seems only `event.body` is passed to the handler as `event`. However, the data needed to authenticate the GitHub event is included in `event.headers`, which is not passed to the lambda function when I use serverless-step-functions...

Any way to accomplish what I want, or is this actually a bug?

Minimal serverless.yml to reproduce:

```
service: github-webhook-listener

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    GITHUB_WEBHOOK_SECRET: REPLACE-WITH-YOUR-SECRET-HERE

functions:
  githubWebhookListener:
    handler: handler.githubWebhookListener

stepFunctions:
  stateMachines:
    webhook-listener:
      events:
        - http:
            path: webhook
            method: POST
            cors: true
      definition:
        Comment: "Listen for Github webhook"
        StartAt: receive_webhook
        States:
          receive_webhook:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:#{AWS::StackName}-githubWebhookListener"
            End: true
```

Error in CloudWatch:
```
TypeError: Cannot read property 'X-Hub-Signature' of undefined at module.exports.githubWebhookListener (/var/task/handler.js:13:22)
```

I confirmed that the event structure is different by modifying handler.js to log the event:

```
diff --git a/handler.js b/handler.js
index a4d47b0..a82dfb0 100644
--- a/handler.js
+++ b/handler.js
@@ -5,6 +5,8 @@ function signRequestBody(key, body) {
 }

 module.exports.githubWebhookListener = (event, context, callback) => {
+  console.log("REQUEST RECEIVED:\n" + JSON.stringify(event));
+
   var errMsg; // eslint-disable-line
   const token = process.env.GITHUB_WEBHOOK_SECRET;
   const headers = event.headers;
```

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.20.2
* ***The Plugin Version you're using***: serverless-pseudo-parameters@1.1.5
* ***Operating System***: Windows
* ***Stack Trace***: None
* ***Provider Error messages***: See above
