### ISSUE TITLE
Change the name of the state machine for environment

### ISSUE THREAD

**Issue by jnst** [horike37/serverless-step-functions#75]
Can I change the name of the state machine for each environment?

## Description

I have some environments like `dev`, `stg`, `prod`.
I can not distinguish it because it is similarly named when I deploy. It has the following format.

- MySampleStepFunctionsStateMachine-GBSNBHDLUUV6
- MySampleStepFunctionsStateMachine-WLVXTYFB5TAM

Is there any solution?

### serverless.yml

```yaml
stepFunctions:
  stateMachines:
    MySample:
      definition:
        Comment: "my sample step functions"
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${self:provider.stage}-FirstState
            Next: SecondState
          SecondState:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${self:provider.stage}-SecondState
            End: true
```

**Comment by danielsig727** [comment]
I'm naming my state machine name as `SomeStateMachine${opt:stage}` in my `serverless.yaml` and it works so far.
Actually I also tried `SomeStateMachine-${opt:stage}` previously but somehow the package always "escapes" character `-` to `dash` (so it will be shown as something like `SomeStateMachinedashproduction` in AWS stepf console), and also `_` will be replaced by `underscore`, which is ugly. :/

**Comment by horike37** [comment]
Sorry for the delay response @jnst 

>Is there any solution?
Yup, we have provided the following solution to name to the each statemachine.
https://github.com/horike37/serverless-step-functions/blob/master/README.md#adding-a-custom-name-for-a-statemachine

This would be helpful for you.

Thank you for following up @danielsig727! Yes you are right 💯 

Closing this issue. Free feel to re-open if you have something to reply 👍

**Comment by jnst** [comment]
Thank you for giving me an answer! 👍
I decided to adopt camelcase simply. It is the following way.


```yaml
custom:
  dev:
    stepFunctionsName: Dev
  stg:
    stepFunctionsName: Stg
  prod:
    stepFunctionsName: Prod

stepFunctions:
  stateMachines:
    MySample:
      name: MySample${self:custom.${opt:stage}.stepFunctionsName}
```


- Result
  - MySampleDev-Z2F7E2Z6OJOY
  - MySampleStg-2ZDKWO9SFGVT
  - MySampleProd-WLVXTYFB5TAM
