### ISSUE TITLE
When trying to provide ARN as env variable: Template format error: Unresolved resource dependencies

### ISSUE THREAD

**Issue by dggriffin** [horike37/serverless-step-functions#78]
## Description

**Serverless Version:** 
1.22.0

**Serverless Step Function Version:**
1.2.0

**Stack Trace:**
` The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [studio-etldevetlStateMachine] in the Resources block of the template
`

**Example YAML:**

```
functions:
  apiTrigger:
    handler: src/handlers/apiTrigger.handler
    name: ${self:service}-${opt:stage}-ApiTrigger
    description: ETL process trigger through API gateway
    events:
      - http:
          path: attributes/{sku}
          method: get
          request:
            parameters:
              paths:
                sku: true
    environment:
      STATE_MACHINE_ARN: ${self:resources.Outputs.etlStateMachine.Value}

...

stepFunctions:
  stateMachines:
    etlStateMachine:
      name: ${self:service}${opt:stage}etlStateMachine
      events:
        - http:
            path: etl-trigger
            method: GET
      definition:
        Comment: "An example of the Amazon States Language using wait states"
        StartAt:  read_queue
        States:
          read_queue:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-CheckQueue
          End: true

...

resources:
  Outputs:
    etlStateMachine:
      Value:
        Ref: ${self:service}${opt:stage}etlStateMachine

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

```

Fails without a dynamic step function name as well.

**Comment by timoahokas** [comment]
I'm running into this too. If this is a regression, any idea in which versions this still worked?

**Comment by cvwj** [comment]
I'm also experiencing this issue. I want to start a stepfunction from a lambda, but I get:

      A valid service attribute to satisfy the declaration 'self:resources.Outputs.ProcessLead.Value' could not be found.


    Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           5.5.0
     Serverless Version:     1.22.0

**Comment by cvwj** [comment]
The problem relates to the name of the stepfunction first being known when cloudformation has completed its work. At that time, the lambda function has already been created, and it's too late.

Could a solution be that you in advance to deployment could define the final name of the stepfunctions, so you could reference it by its arn:
  
`arn:aws:states:${self:provider.region}:${self:custom.accountId}:stateMachine:${self:stepFunctions.stateMachines.processLead}`

**Comment by cvwj** [comment]
I hereby retract my comment - everything works if you read the documentation. One need to specify the section for Outputs:

```
resources:
  Outputs:
     ProcessLead:
       Description: "The ARN of the StateMachine for processing leads"
       Value:
        Ref: ProcessLead
```

Then I can reference the ARN in my Lambda function like this:

```
functions:
  store_lead:
    handler: lambdas/store_lead.lambda_handler
    MemorySize: 128
    environment:
      STATEMACHINE_PROCESSLEAD: ${self:resources.Outputs.ProcessLead.Value}

```

**Comment by timoahokas** [comment]
It seems to work ok for me when I use a static name for the StateMachine (without name attribute including dynamic component e.g. ${opt:stage}. But when using a dynamic name, it fails with the mentioned error:

  The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [timodevMyStateMachine] in the Resources block of the template

Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [timodevMyStateMachine] in the Resources block of the template
    at provider.request.catch (/Users/tahokas/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:25:13)
From previous event:
    at AwsDeploy.validateTemplate (/Users/tahokas/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:12)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/Users/tahokas/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:117:39)
From previous event:
    at Object.aws:deploy:deploy:validateTemplate [as hook] (/Users/tahokas/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:113:10)
    at BbPromise.reduce 
...

My definition:

stepFunctions:
 stateMachines:
   MyStateMachine:
     name: ${opt:stage}MyStateMachine
     definition:
       StartAt: StepOne
       States:
         StepOne:
           Type: Task
           Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${opt:stage}-stepOne
           Next: StepTwo
         StepTwo:
           Type: Task
           Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${opt:stage}-stepTwo
           End: true

resources:
 Outputs:
   MyStateMachine:
     Value:
       Ref: ${env:STAGE}MyStateMachine

Also, if I try to use ${opt:stage} in the Output section, I get:

  Serverless Error ---------------------------------------

  Trying to populate non string value into a string for variable ${opt:stage}. Please make sure the value of the property is a string.

Out provider section has:

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:STAGE}

Is this supposed to work with dynamic names for the StateMachine?

**Comment by hanzenlim** [comment]
Yea looks like something changed in the cloud formation template. This value ${self:resources.Outputs.MyStateMachine.Value} is returning object instead of a string.

**Comment by horike37** [comment]
Thanks, everyone here for discussing 👍
Seems that the spec of this plugin caused those problems..

To generate Logical ID for CloudFormation, the plugin transform the specified name in serverless.yml based on the following scheme.

- Transform a leading character into uppercase
- Transform  `-` into `Dash`
- Transform  `-` into `Underscore`

If you want to user variables system in `name` statement, you can't put the variables as a leading character since the variables are transformed within `Output` section, as a result, the reference is broken.

The correct sample is here.
```yaml
stepFunctions:
  stateMachines:
    etlStateMachine:
      name: etlStateMachine-${self:service}-${opt:stage}
      events:
        - http:
            path: etl-trigger
            method: GET
      definition:
        Comment: "An example of the Amazon States Language using wait states"
        StartAt:  read_queue
        States:
          read_queue:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-CheckQueue
          End: true

...

resources:
  Outputs:
    etlStateMachine:
      Value:
        Ref: EtlStateMachineDash${self:service}Dash${opt:stage}
```
