### ISSUE TITLE
Question: How to setting schedule event for each environment

### ISSUE THREAD

**Issue by jnst** [horike37/serverless-step-functions#79]
# This is a Question

## Description

Thanks support for schedule event <3

I have a question. Can I set up separate schedule events for each environment?
I can not come up of anything other than comment out or `enable: false` before deploy it.

```yaml
stepFunctions:
  stateMachines:
    MyBatchProc:
      events:
        - schedule:
            description: "for development environment"
            rate: cron(2,12,22,32,42,52 * * * ? *)
            enabled: true
        - schedule:
            description: "for staging environment"
            rate: cron(1 4,12,20 * * ? *)
            enabled: true
        - schedule:
            description: "for product environment"
            rate: cron(2 5,13,21 * * ? *)
            enabled: true
```

**Comment by horike37** [comment]
Thank you for opening this @jnst !
How do you want to separate for each environment?
Could you share more what you want so that we can help you?

**Comment by horike37** [comment]
@jnst 
Ah, OK I just got what you want. Just a while.

**Comment by horike37** [comment]
You can set up something like this to do what you want with `custom` variables feature.
Could you try again?

```yaml
custom:
  scheduledRate:
    development: cron(2,12,22,32,42,52 * * * ? *)
    staging: cron(1 4,12,20 * * ? *)
    product: cron(2 5,13,21 * * ? *)
    
stepFunctions:
  stateMachines:
    MyBatchProc:
      events:
        - schedule:
            rate: ${self:custom.scheduledRate.${opt:stage}}
```
