### ISSUE TITLE
Support custom http request templates

### ISSUE THREAD

**Issue by dbaghdanov** [horike37/serverless-step-functions#92]
# Feature Proposal

## Description
I'd like be be able to customize the events / http / request / template.  I'd like to add my own content-type definitions, and even override the build in definitions for `application/json`.

For feature proposals:
* Currently
  * Currently a default Body Mapping Template is used which defines a mapping for `application/json` and `application/x-www-form-urlencoded`.
  * Currently the events / http / request / template is completely  ignored if it's included.
* Proposed
  * Let the script provide a request / template only if none is provided, or a match isn't found.
```
stepFunctions:
  stateMachines:
    myStateMachine:
      events:
        - http:
            path: orders/{id}
            method: POST
            request:
              template:
                application/xml: '{"input": "$input.body", "stateMachineArn": "arn:aws:states:region:account:stateMachine:myStateMachine"}'
              parameters:
                paths:
                  id: true
```

## Additional Data
* ***Serverless Framework Core Version you're using***: 
  * 1.23.0
* ***The Plugin Version you're using***:
  * 1.3.0
* ***Operating System***:
  * Windows 7
