### ISSUE TITLE
Refer to step function by name instead of arn

### ISSUE THREAD

**Issue by ballwood** [horike37/serverless-step-functions#98]
# This is a Feature Proposal

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Currently serverless-step-functions uses the arn in the resource field. It would be useful to use allow the lambda name which is later resolved to an arn on deploy so it can validate the function exists.

* If there is additional config how would it look

````
functions:
  step:
    handler: functions/step.handler

stepFunctions:
  stateMachines:
    test:
      name: test-${self:service}-${opt:stage}
      definition:
        Comment: "Test step function"
        StartAt: TestStep
        States:
          TestStep:
            Type: Task
            Resource: step
            End: true
````

@horike37 I've written a function to traverse the definition tree already and can do a pull request, just need advice on the config shown above and exactly what to put in the CF output template (not sure if I can use a ref or if I would have to generate the long arn).

**Comment by horike37** [comment]
Hi @ballwood, thank you for the effort 👍 
However, 100% not sure that, to specify Resource definition by a raw lambda name like `step` would be dangerous since a raw one would an indefinable boundary whether an identifier which means ARN or not. And that would lead users and the implementation to make confusing.

My favorite suggestion for that is to use [Global Arn parser](https://github.com/serverless/serverless/issues/3212)(the functionality is not introduced yet) 

What do you think?

**Comment by ballwood** [comment]
Yeah makes sense to keep it as a centralized utility function, from the issue though I can’t really make out what the implementation should be?

**Comment by theburningmonk** [comment]
This is already supported, as this:

```
functions:
  step:
    handler: functions/step.handler

stepFunctions:
  stateMachines:
    test:
      name: test-${self:service}-${opt:stage}
      definition:
        Comment: "Test step function"
        StartAt: TestStep
        States:
          TestStep:
            Type: Task
            Resource:
              Fn::GetAtt: [step, Arn]
            End: true
```
